import React, { useMemo, useState } from 'react';
import { Building2, Flag, Handshake, HeartPulse, GraduationCap, Route, Shield, Cpu, UsersRound, MapPinned, AlertTriangle } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import BrazilPoliticalMap from './BrazilPoliticalMap';
import { CharacterDossierPanel } from './CharacterDossier';
import { toast } from './sonner';

const INVESTS=[['infraestrutura','Infraestrutura',Route],['saude','Saúde',HeartPulse],['educacao','Educação',GraduationCap],['seguranca','Segurança',Shield],['tecnologia','Tecnologia',Cpu]];
const tone=a=>a>=60?'text-success':a>=45?'text-warning':'text-danger';

export default function Federation({initialUF='SP'}){
  const {estados=[],gruposSociais={},investirEstado,conversarGovernador,eventoFederativoAtivo,historicoEventosFederativos=[]}=useGameStore();
  const [uf,setUf]=useState(initialUF); const [tab,setTab]=useState('visao'); const [imgError,setImgError]=useState(false); const [flagError,setFlagError]=useState(false);
  const e=estados.find(x=>x.uf===uf)||estados[0];
  const grupos=useMemo(()=>Object.entries(e?.composicao||{}).sort((a,b)=>b[1]-a[1]).slice(0,5),[e]);
  if(!e)return null;
  const investir=(tipo)=>{const r=investirEstado(e.uf,tipo);r.ok?toast.success(`Investimento autorizado em ${e.nome}.`):toast.error('Não foi possível investir.');};
  const conversar=(estrategia)=>{conversarGovernador(e.uf,estrategia);toast.success('Movimento federativo registrado.');};
  return <div className="ui-page h-full min-h-0 overflow-hidden">
    <div className="grid h-full min-h-0 gap-4 xl:grid-cols-[.82fr_1.18fr]">
      <section className="min-h-0 overflow-hidden rounded-2xl border border-border bg-card/65 p-4"><div className="mb-3 flex items-center justify-between"><div><div className="ui-kicker">Federação</div><h2 className="text-lg font-black">Mapa de apoio presidencial</h2></div><span className="ui-chip">27 UFs</span></div><div className="h-[calc(100%-56px)]"><BrazilPoliticalMap estados={estados} selected={e.uf} onSelect={(x)=>{setUf(x);setTab('visao');setImgError(false);setFlagError(false)}}/></div></section>
      <section className="min-h-0 overflow-hidden rounded-2xl border border-border bg-card/65">
        <div className="relative h-[190px] overflow-hidden border-b border-border bg-panel">
          {!imgError?<img src={e.capitalImage} onError={()=>setImgError(true)} alt={`Capital de ${e.nome}`} className="h-full w-full object-cover opacity-55"/>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(23,128,106,.28),transparent_45%),linear-gradient(135deg,rgba(255,255,255,.04),transparent)]"/>}
          <div className="absolute inset-0 bg-gradient-to-t from-card via-card/40 to-transparent"/>
          <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 p-5"><div className="flex items-center gap-4">{!flagError?<img src={e.flagImage} onError={()=>setFlagError(true)} className="h-14 w-20 rounded-lg border border-white/15 object-cover shadow-elevation-2" alt={`Bandeira de ${e.nome}`}/>:<div className="grid h-14 w-20 place-items-center rounded-lg border border-border bg-panel text-lg font-black">{e.uf}</div>}<div><div className="ui-kicker">{e.regiao} · capital {e.capital}</div><h2 className="text-3xl font-black tracking-[-.04em]">{e.nome}</h2></div></div><div className="text-right"><div className="ui-data-label">Aprovação</div><div className={`text-3xl font-black ${tone(e.aprovacao)}`}>{Math.round(e.aprovacao)}%</div></div></div>
        </div>
        <div className="flex border-b border-border px-4 pt-2">{[['visao','Estado'],['governador','Governador'],['investir','Investimentos'],['eleitorado','Eleitorado'],['tensoes','Tensões']].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`ui-tab ${tab===id?'ui-tab-active':''}`}>{l}</button>)}</div>
        <div className="h-[calc(100%-238px)] min-h-0 overflow-hidden p-5">
          {tab==='visao'&&<div className="grid h-full gap-4 md:grid-cols-2"><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="ui-kicker">Prioridade estadual</div><h3 className="mt-2 text-xl font-black">{e.prioridade}</h3><p className="mt-3 text-sm leading-relaxed text-muted">Investimentos federais mudam aprovação local, relação com o governador, capacidade de articulação da bancada e a trajetória fiscal nacional.</p></div><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="ui-kicker">Ponte com Brasília</div><div className="mt-2 flex items-end justify-between"><span className="text-sm font-bold">Relação com Planalto</span><b className={tone(e.relacaoPlanalto)}>{Math.round(e.relacaoPlanalto)}%</b></div><div className="mt-3 h-2 rounded bg-bg"><div className="h-full rounded bg-success" style={{width:`${e.relacaoPlanalto}%`}}/></div><p className="mt-4 text-xs text-muted">Um governador aliado ajuda em bancadas estaduais, obras e campanha; um governador rival pode nacionalizar conflitos locais.</p></div></div>}
          {tab==='governador'&&<div className="h-full overflow-y-auto pr-1"><CharacterDossierPanel person={e.governador} eyebrow={`Governador · ${e.uf}`} subtitle={`${e.governador.partido} · ${e.governador.ideologia} · ${e.governador.estilo}`} imageKey={e.governador.avatar||`gov-${e.uf}-${e.governador.nome}`} stats={[{label:'Popularidade',value:e.governador.popularidade,suffix:'%'},{label:'Relação',value:e.governador.relacao,suffix:'%'},{label:'Ambição',value:e.governador.ambicao},{label:'Aprovação local',value:e.aprovacao,suffix:'%'}]}/><div className="mt-4 grid grid-cols-3 gap-2"><button className="ui-btn-secondary justify-center" onClick={()=>conversar('pacto')}><Handshake size={15}/> Pacto</button><button className="ui-btn-secondary justify-center" onClick={()=>conversar('prestigiar')}><UsersRound size={15}/> Prestigiar</button><button className="ui-btn-secondary justify-center" onClick={()=>conversar('pressionar')}><Flag size={15}/> Pressionar</button></div></div>}
          {tab==='investir'&&<div className="grid h-full grid-cols-2 gap-3 lg:grid-cols-3">{INVESTS.map(([id,label,Icon])=><button key={id} onClick={()=>investir(id)} className="group rounded-2xl border border-border bg-panel/40 p-4 text-left hover:border-success/35"><Icon size={20} className="text-success"/><div className="mt-3 font-black">{label}</div><p className="mt-1 text-xs text-muted">Autorizar pacote federal. O custo entra no resultado primário — não em uma carteira.</p></button>)}<div className="rounded-2xl border border-dashed border-border p-4"><MapPinned size={20} className="text-warning"/><div className="mt-3 font-black">Histórico local</div><p className="mt-1 text-xs text-muted">{e.investimentos?.length||0} investimento(s) federal(is) nesta campanha.</p></div></div>}
          {tab==='eleitorado'&&<div className="grid h-full gap-3 sm:grid-cols-2">{grupos.map(([id,peso])=><div key={id} className="rounded-2xl border border-border bg-panel/40 p-4"><div className="flex items-center justify-between"><span className="text-sm font-black">{gruposSociais[id]?.nome||id}</span><b className={tone(gruposSociais[id]?.aprovacao||50)}>{Math.round(gruposSociais[id]?.aprovacao||50)}%</b></div><div className="mt-2 text-xs text-muted">Peso aproximado no estado: {peso}%</div><div className="mt-3 h-1.5 rounded bg-bg"><div className="h-full rounded bg-info" style={{width:`${peso*2.6}%`}}/></div></div>)}</div>}
          {tab==='tensoes'&&<div className="h-full overflow-y-auto"><div className="ui-kicker">Radar federativo</div><h3 className="mt-1 text-xl font-black">Conflitos que podem nacionalizar a política</h3>{eventoFederativoAtivo?.uf===e.uf&&<div className="mt-4 rounded-2xl border border-danger/30 bg-danger/5 p-4"><div className="flex items-center gap-2 text-[10px] font-black uppercase text-danger"><AlertTriangle size={14}/> Evento ativo · ×{eventoFederativoAtivo.multiplicador.toFixed(2)}</div><div className="mt-2 font-black">{eventoFederativoAtivo.titulo}</div><p className="mt-2 text-xs leading-relaxed text-muted">{eventoFederativoAtivo.texto}</p><div className="mt-3 text-[10px] font-black text-warning">A resposta está pendente no gabinete presidencial.</div></div>}<div className="mt-4 space-y-2">{historicoEventosFederativos.filter(x=>x.uf===e.uf).map(x=><div key={x.instanceId||x.id} className="rounded-xl border border-border bg-panel/40 p-3"><div className="text-[9px] font-black uppercase text-muted">Turno {x.resolvidoNoTurno} · impacto ×{x.multiplicador?.toFixed?.(2)||'1.00'}</div><div className="mt-1 text-xs font-black">{x.titulo}</div><div className="mt-2 text-[10px] text-info">Resposta: {x.resposta}</div></div>)}{!historicoEventosFederativos.some(x=>x.uf===e.uf)&&eventoFederativoAtivo?.uf!==e.uf&&<div className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted">Nenhuma crise federativa de alta saliência registrada neste estado ainda.</div>}</div></div>}
        </div>
      </section>
    </div>
  </div>;
}
