import React, { useMemo, useState } from 'react';
import { BookOpen, Crown, Flag, Gavel, History, Landmark, Scale, Search, ShieldCheck, Sparkles, Star, Trophy } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import { construirLegadoLegislativo } from '../game/legislativeLegacyEngine.js';
import GameIcon from './GameIcon';
import { toast } from './sonner';

const CAT={economia:'Economia',tributacao:'Tributação',trabalho:'Trabalho',saude:'Saúde',educacao:'Educação',seguranca:'Segurança',sociedade:'Sociedade',ambiental:'Meio ambiente',agro:'Agro',infraestrutura:'Infraestrutura',digital:'Digital',institucional:'Institucional',geopolitica:'Defesa & Exterior'};
const toneClass=(tone)=>tone==='success'?'text-success border-success/30 bg-success/5':tone==='warning'?'text-warning border-warning/30 bg-warning/5':tone==='danger'?'text-danger border-danger/30 bg-danger/5':tone==='info'?'text-info border-info/30 bg-info/5':'text-muted border-border bg-panel/40';
const scoreTone=(n)=>n>=80?'text-success':n>=65?'text-info':n>=45?'text-warning':'text-danger';

function ScoreRing({score=0,size='lg'}){
  const dim=size==='sm'?54:74;
  return <div className="relative grid shrink-0 place-items-center rounded-full border border-border bg-bg/70" style={{width:dim,height:dim}}><div className={`font-mono ${size==='sm'?'text-base':'text-xl'} font-black ${scoreTone(score)}`}>{Math.round(score)}</div><div className="absolute bottom-1 text-[7px] font-black uppercase tracking-widest text-muted">legado</div></div>;
}

function LawLegacyCard({entry,isFlagged,onFlag}){
  const [open,setOpen]=useState(false);
  return <article className={`rounded-2xl border bg-card/72 p-4 transition-colors ${isFlagged?'border-warning/35':'border-border'}`}>
    <div className="flex items-start gap-3"><ScoreRing score={entry.score}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><span className="ui-chip">{entry.instrumento}</span><span className="ui-chip">{CAT[entry.categoria]||entry.categoria}</span><span className={`ui-chip ${toneClass(entry.tier.tone)}`}>{entry.tier.label}</span>{isFlagged&&<span className="ui-chip border-warning/30 bg-warning/5 text-warning"><Flag size={10}/> Bandeira</span>}</div><h4 className="mt-2 text-base font-black leading-tight">{entry.titulo}</h4><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-muted">Origem: {entry.origem}{entry.versao?` · texto v${entry.versao}`:''}</p></div></div>
    {entry.status==='vigente'&&<div className="mt-4 grid grid-cols-2 gap-2 text-[10px] sm:grid-cols-4"><div className="rounded-xl border border-border bg-panel/35 p-2.5"><div className="ui-data-label">Regulação</div><div className="mt-1 font-bold text-text">{entry.regulacao?.status==='regulamentada'?'Concluída':entry.regulacao?'Pendente':'Direta'}</div></div><div className="rounded-xl border border-border bg-panel/35 p-2.5"><div className="ui-data-label">Programas</div><div className="mt-1 font-bold text-text">{entry.programas.length}</div></div><div className="rounded-xl border border-border bg-panel/35 p-2.5"><div className="ui-data-label">STF</div><div className="mt-1 font-bold text-text">{entry.casosSTF.length?entry.casosSTF.at(0)?.status:'Sem ação'}</div></div><div className="rounded-xl border border-border bg-panel/35 p-2.5"><div className="ui-data-label">TCU</div><div className="mt-1 font-bold text-text">{entry.auditoriasTCU.length?entry.auditoriasTCU.at(0)?.status:'Sem auditoria'}</div></div></div>}
    {open&&<div className="mt-4 space-y-4 border-t border-border pt-4"><div className="grid gap-2 md:grid-cols-2"><div className="rounded-xl border border-border bg-panel/30 p-3"><div className="ui-data-label">Potencial de legado</div><p className="mt-1 text-xs leading-relaxed text-muted">{entry.legadoPotencial||'O efeito estrutural dependerá da implementação e da estabilidade institucional.'}</p></div><div className="rounded-xl border border-border bg-panel/30 p-3"><div className="ui-data-label">Leitura atual</div><div className="mt-2 space-y-1 text-[10px] text-muted">{entry.regResumo&&<p>• {entry.regResumo}</p>}{entry.progResumo&&<p>• {entry.progResumo}</p>}{entry.stfResumo&&<p>• {entry.stfResumo}</p>}{entry.tcuResumo&&<p>• {entry.tcuResumo}</p>}</div></div></div><div><div className="flex items-center gap-2"><History size={13} className="text-info"/><div className="ui-section-title">Jornada da lei</div></div><div className="mt-2 max-h-52 space-y-2 overflow-y-auto pr-1 custom-scrollbar">{entry.timeline.map(item=><div key={item.id} className="flex gap-3 text-[11px]"><div className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-info"/><div><b className="text-text">Mês {item.turno||'—'} · {item.tipo}</b><p className="mt-0.5 text-muted">{item.texto}</p></div></div>)}</div></div></div>}
    <div className="mt-4 flex items-center justify-between border-t border-border pt-3"><button onClick={()=>setOpen(v=>!v)} className="ui-btn-ghost px-0 text-xs">{open?'Recolher histórico':'Abrir jornada'} <BookOpen size={13}/></button>{entry.status==='vigente'&&<button onClick={onFlag} className={`ui-btn-secondary ${isFlagged?'border-warning/30 text-warning':''}`}><Flag size={13}/>{isFlagged?'Retirar bandeira':'Assumir como bandeira'}</button>}</div>
  </article>;
}

export default function LegislativeLegacy(){
  const store=useGameStore();
  const {legadoLegislativo,alternarBandeiraLegislativa}=store;
  const resumo=useMemo(()=>construirLegadoLegislativo(store),[store.votacoes,store.leisDisponiveis,store.controleLeis,store.regulamentacaoLeis,store.programas,legadoLegislativo]);
  const [filter,setFilter]=useState('vigentes'); const [search,setSearch]=useState('');
  const bandeiras=new Set(legadoLegislativo?.bandeiras||[]);
  const list=resumo.entradas.filter(e=>{if(filter==='vigentes'&&e.status!=='vigente')return false;if(filter==='emblematicas'&&e.score<80)return false;if(filter==='contestadas'&&!(e.status==='vigente'&&e.score<45))return false;if(filter==='encerradas'&&!['arquivada','vetada','invalidada'].includes(e.status))return false;const q=search.trim().toLowerCase();return !q||`${e.titulo} ${e.categoria} ${e.origem}`.toLowerCase().includes(q)});
  const toggle=(e)=>{const r=alternarBandeiraLegislativa(e.leiId);r?.ok?toast.success(bandeiras.has(e.leiId)?'Lei retirada das bandeiras do mandato.':'Lei assumida como bandeira presidencial.'):toast.error(r?.motivo||'Não foi possível alterar a bandeira.');};
  return <div className="space-y-4 animate-fadeIn">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><div className="ui-stat xl:col-span-1"><div className="flex items-center gap-3"><GameIcon icon={Crown} tone={resumo.indice>=75?'warning':'violet'}/><div><div className="ui-data-label">Índice de legado</div><div className={`mt-1 text-3xl font-black ${scoreTone(resumo.indice)}`}>{resumo.indice}<span className="text-xs text-muted">/100</span></div></div></div></div><div className="ui-stat"><div className="ui-data-label">Leis vigentes</div><div className="mt-1 text-2xl font-black">{resumo.vigentes}</div><p className="mt-1 text-[9px] text-muted">{resumo.cobertura}% das áreas cobertas</p></div><div className="ui-stat"><div className="ui-data-label">Emblemáticas</div><div className="mt-1 text-2xl font-black text-success">{resumo.emblematicas.length}</div><p className="mt-1 text-[9px] text-muted">score ≥ 80</p></div><div className="ui-stat"><div className="ui-data-label">Regulamentação</div><div className="mt-1 text-2xl font-black">{resumo.taxaRegulacao}%</div><p className="mt-1 text-[9px] text-muted">{resumo.reguladas} concluída(s)</p></div><div className="ui-stat"><div className="ui-data-label">Programas derivados</div><div className="mt-1 text-2xl font-black text-info">{resumo.programasDerivados}</div><p className="mt-1 text-[9px] text-muted">leis que viraram entrega</p></div></section>

    <section className="ui-surface p-4 md:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Trophy size={17} className="text-warning"/><p className="ui-kicker">Livro do mandato</p></div><h3 className="mt-1 text-lg font-black">Bandeiras legislativas da Presidência</h3><p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted">Escolha até três leis para associar diretamente ao seu legado. Elas ganham peso maior no índice — e, na fase eleitoral, o desempenho dessas bandeiras passa a compor a memória do mandato.</p></div><span className="ui-chip border-warning/25 bg-warning/5 text-warning"><Flag size={11}/>{bandeiras.size}/3 bandeiras</span></div><div className="mt-4 grid gap-3 md:grid-cols-3">{[0,1,2].map(i=>{const id=[...bandeiras][i];const e=resumo.entradas.find(x=>x.leiId===id);return <div key={i} className={`min-h-24 rounded-2xl border p-4 ${e?'border-warning/25 bg-warning/5':'border-dashed border-border bg-panel/20'}`}>{e?<><div className="flex items-center justify-between"><Flag size={15} className="text-warning"/><b className={scoreTone(e.score)}>{e.score}/100</b></div><div className="mt-2 text-sm font-black">{e.titulo}</div><div className="mt-1 text-[10px] text-muted">{e.tier.label}</div></>:<div className="grid h-full place-items-center text-center text-xs text-muted">Bandeira disponível<br/>Escolha uma lei vigente abaixo</div>}</div>})}</div></section>

    {resumo.categoriasResumo.length>0&&<section className="ui-surface p-4"><div className="flex items-center gap-2"><Sparkles size={15} className="text-info"/><div className="ui-section-title">Pegada legislativa do mandato</div></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1 custom-scrollbar">{resumo.categoriasResumo.map(c=><div key={c.id} className="min-w-36 rounded-xl border border-border bg-panel/35 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-muted">{CAT[c.id]||c.id}</div><div className={`mt-1 text-xl font-black ${scoreTone(c.score)}`}>{c.score}</div><div className="text-[9px] text-muted">{c.quantidade} lei(s)</div></div>)}</div></section>}

    <section className="ui-surface p-4 md:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="ui-kicker">Arquivo legislativo</p><h3 className="mt-1 text-base font-black">O que este governo deixará escrito</h3></div><div className="relative min-w-60"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lei…" className="h-9 w-full rounded-xl border border-border bg-bg/70 pl-9 pr-3 text-xs"/></div></div><div className="mt-3 flex gap-2 overflow-x-auto">{[['vigentes','Vigentes'],['emblematicas','Emblemáticas'],['contestadas','Contestadas'],['encerradas','Vetadas / arquivadas'],['todas','Todas']].map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`ui-chip shrink-0 ${filter===id?'border-info/40 bg-info/5 text-info':''}`}>{label}</button>)}</div><div className="mt-4 grid gap-3 xl:grid-cols-2">{list.map(e=><LawLegacyCard key={e.propostaId} entry={e} isFlagged={bandeiras.has(e.leiId)} onFlag={()=>toggle(e)}/>)}{!list.length&&<div className="col-span-full rounded-2xl border border-dashed border-border p-10 text-center"><Landmark size={28} className="mx-auto text-muted/35"/><h4 className="mt-3 font-black">Nenhuma lei neste recorte</h4><p className="mt-1 text-xs text-muted">O legado começa a ganhar forma quando propostas chegam ao fim da tramitação.</p></div>}</div></section>

    {(legadoLegislativo?.marcos||[]).length>0&&<section className="ui-surface p-4"><div className="flex items-center gap-2"><Star size={15} className="text-warning"/><div className="ui-section-title">Marcos do mandato</div></div><div className="mt-3 grid gap-2 md:grid-cols-2">{(legadoLegislativo.marcos||[]).slice(0,8).map(m=><div key={m.key} className="rounded-xl border border-border bg-panel/35 p-3"><div className="flex items-center justify-between"><span className="text-[9px] font-black uppercase tracking-wider text-warning">Mês {m.turno}</span><span className="font-mono text-xs font-black">{m.score}</span></div><div className="mt-1 text-xs font-bold">{m.texto}</div></div>)}</div></section>}
  </div>;
}
