import React, { useEffect, useMemo, useState } from 'react';
import { Briefcase, AlertTriangle, UserPlus, BrainCircuit, MessageSquare, ShieldAlert, Activity, Crown, HeartHandshake, Gauge, Sparkles, UsersRound, Phone, Target, Network, FileWarning, ChevronRight, CalendarRange } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import NomeacaoModal from './NomeacaoModal';
import PoliticalAvatar from './PoliticalAvatar';
import MinistryChallengeModal from './MinistryChallengeModal';
import NationalEventsPanel from './NationalEventsPanel';
import CabinetCouncilModal from './CabinetCouncilModal';
import { desafiosDaPasta, avaliarMinistro } from '../game/ministryEngine';
import { toast } from './sonner';

const Meter=({label,value,tone='bg-info'})=><div><div className="mb-1 flex justify-between text-[9px] font-black uppercase tracking-wider text-muted"><span>{label}</span><span className="text-text">{Math.round(value||0)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-panel"><div className={`h-full ${tone}`} style={{width:`${Math.max(0,Math.min(100,value||0))}%`}}/></div></div>;

export default function Ministries(){
  const { cargos=[], nomeacoes=[], conflitosMinisteriais=[], definirPrioridade, resolverDemanda, intervirMinisterio, conversarComMinistro, turno }=useGameStore();
  const [activeId,setActiveId]=useState(null); const [modalCargo,setModalCargo]=useState(null); const [desafio,setDesafio]=useState(null); const [tab,setTab]=useState('gabinete'); const [conselho,setConselho]=useState(false);
  useEffect(()=>{if(cargos.length&&!activeId)setActiveId(cargos[0].id)},[cargos,activeId]);
  if(!cargos.length)return <div className="p-8 text-center text-muted">Carregando ministérios...</div>;
  const cargo=cargos.find(c=>c.id===activeId)||cargos[0]; const ministro=nomeacoes.find(n=>n.cargoId===cargo.id); const metricas=avaliarMinistro(ministro); const desafios=desafiosDaPasta(cargo.id);
  const resolver=(aceitou)=>{const r=resolverDemanda(cargo.id,aceitou); if(!r?.ok)toast.error(r?.motivo||'Ação indisponível'); else toast.success(aceitou?'Resposta autorizada':'Demanda adiada');};
  const conversa=(tom)=>{const r=conversarComMinistro(cargo.id,tom); if(!r?.ok)toast.error(r.motivo); else toast.success(r.resumo)};
  const conflitos=conflitosMinisteriais.filter(c=>c.origem===cargo.id||c.destino===cargo.id);

  return <div className="ui-page h-full min-h-0 overflow-hidden">
    <div className="ui-surface flex h-full min-h-0 flex-col overflow-hidden p-0 lg:flex-row">
      <aside className="flex w-full shrink-0 flex-col border-b border-border bg-panel/75 lg:w-[270px] lg:border-b-0 lg:border-r">
        <div className="border-b border-border px-4 py-4"><div className="ui-kicker">Esplanada</div><div className="mt-1 text-sm font-black text-text">Ministérios do Governo</div></div>
        <div className="flex gap-2 overflow-x-auto p-2.5 lg:min-h-0 lg:flex-1 lg:flex-col lg:overflow-y-auto">{cargos.map(c=>{const n=nomeacoes.find(x=>x.cargoId===c.id); const active=c.id===cargo.id; return <button key={c.id} onClick={()=>{setActiveId(c.id);setTab('gabinete')}} className={`flex min-w-[210px] items-center gap-3 rounded-xl border px-3 py-3 text-left transition lg:min-w-0 lg:w-full ${active?'border-success/35 bg-success/5':'border-transparent hover:border-border hover:bg-card/55'}`}><PoliticalAvatar name={n?.nome||c.nome} seed={n?.avatarSeed||n?.id||c.id} size={40}/><div className="min-w-0 flex-1"><div className={`truncate text-xs font-black ${active?'text-text':'text-text/80'}`}>{c.nome}</div><div className="mt-0.5 truncate text-[10px] text-muted">{n?.nome||'Cargo vago'}</div></div><div className="flex items-center gap-1">{c.status==='crise'?<span className="h-2 w-2 rounded-full bg-danger"/>:c.demandaAtual?<span className="h-2 w-2 rounded-full bg-warning"/>:null}<ChevronRight size={13} className={active?'text-success':'text-muted/40'}/></div></button>})}</div>
        <div className="border-t border-border p-3"><button onClick={()=>setConselho(true)} className="ui-btn-secondary w-full justify-center"><UsersRound size={16}/> Convocar Conselho</button></div>
      </aside>

      <main className="flex min-h-0 min-w-0 flex-1 flex-col bg-bg/30">
        <header className="border-b border-border bg-panel/35 px-5 py-5 md:px-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 items-center gap-4"><PoliticalAvatar name={ministro?.nome||cargo.nome} seed={ministro?.avatarSeed||ministro?.id||cargo.id} size={66}/><div className="min-w-0"><div className="ui-kicker">{cargo.pasta} · {cargo.nome}</div><h2 className="mt-1 truncate text-2xl font-black text-text">{ministro?.nome||'Ministério sem liderança'}</h2><p className="mt-1 truncate text-xs font-bold text-muted">{ministro?`${ministro.carreira} · ${ministro.vinculo||ministro.ideologia}`:cargo.descricao}</p></div></div><div className="flex flex-wrap items-center gap-2"><div className="ui-tabs">{[['gabinete','Gabinete'],['operacoes','Operações'],['eventos','Eventos']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`ui-tab ${tab===id?'ui-tab-active':''}`}>{label}</button>)}</div>{ministro&&<button onClick={()=>setModalCargo(cargo)} className="ui-btn-secondary">Trocar ministro</button>}</div></div></header>

        <div className="min-h-0 flex-1 overflow-y-auto p-5 md:p-6">
          {tab==='gabinete'&&<>{!ministro?<div className="grid min-h-[500px] place-items-center rounded-3xl border border-dashed border-border bg-panel/20 p-8 text-center"><div><div className="mx-auto mb-4 grid h-20 w-20 place-items-center rounded-3xl border border-border bg-card"><UserPlus size={34} className="text-success"/></div><h2 className="text-2xl font-black text-text">{cargo.nome} está sem comando</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-relaxed text-muted">A ausência de ministro reduz execução, deixa o telefone sem interlocutor e faz problemas amadurecerem mais rápido.</p><button onClick={()=>setModalCargo(cargo)} className="ui-btn-primary mt-5"><Briefcase size={17}/> Abrir lista de candidatos</button></div></div>:<div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
            <div className="space-y-5">
              <section className="rounded-3xl border border-border bg-card/70 p-5"><div className="flex flex-col gap-5 md:flex-row"><PoliticalAvatar name={ministro.nome} seed={ministro.avatarSeed||ministro.id} size={104}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="ui-kicker">Dossiê do ministro</div><h3 className="mt-1 text-2xl font-black text-text">{ministro.nome}</h3><p className="text-sm font-bold text-muted">{ministro.ideologia} · {ministro.origem}</p></div><span className="ui-chip">{ministro.vinculo}</span></div><p className="mt-4 text-sm italic leading-relaxed text-text/80">{ministro.frase}</p><p className="mt-3 max-w-3xl text-sm leading-relaxed text-text/70">{ministro.biografia}</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Meter label="Lealdade" value={ministro.lealdade||ministro.lealdadeInicial} tone={(ministro.lealdade||ministro.lealdadeInicial)<40?'bg-danger':'bg-success'}/><Meter label="Eficácia" value={metricas.eficacia}/><Meter label="Risco de rival" value={metricas.riscoRival} tone={metricas.riscoRival>60?'bg-warning':'bg-violet-500'}/><Meter label="Risco de escândalo" value={metricas.riscoEscandalo} tone={metricas.riscoEscandalo>55?'bg-danger':'bg-slate-500'}/></div></section>

              {cargo.demandaAtual&&<section className="rounded-3xl border border-warning/30 bg-warning/5 p-5"><div className="mb-2 flex items-center gap-2 text-warning"><AlertTriangle size={18}/><span className="ui-kicker text-warning">Evento ativo · nível {cargo.demandaAtual.nivel}</span></div><h3 className="text-xl font-black text-text">{cargo.demandaAtual.titulo}</h3><p className="mt-2 text-sm leading-relaxed text-text/75">{cargo.demandaAtual.texto}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>resolver(true)} className="ui-btn-primary"><Activity size={16}/> Autorizar resposta · impacto fiscal R$ {cargo.demandaAtual.custo} mi</button><button onClick={()=>resolver(false)} className="ui-btn-secondary">Adiar</button></div></section>}

              <div className="grid gap-4 md:grid-cols-2"><InfoCard icon={Target} title="Agenda pessoal" text={ministro.agendaPessoal}/><InfoCard icon={Network} title="Rede de poder" text={ministro.rede}/><InfoCard icon={FileWarning} title="Vulnerabilidade" text={ministro.vulnerabilidade} tone="warning"/><InfoCard icon={ShieldAlert} title="Atritos no governo" text={conflitos.length?`${conflitos.length} conflito(s) interministerial(is) ativo(s).`:'Nenhum conflito direto reportado neste momento.'}/></div>
            </div>

            <aside className="space-y-4"><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="mb-3 flex items-center gap-2"><HeartHandshake size={16} className="text-success"/><h3 className="text-sm font-black text-text">Relação com o Presidente</h3></div><div className="grid gap-2"><button onClick={()=>conversa('ouvir')} className="ui-btn-secondary justify-start"><MessageSquare size={15}/> Ouvir em reservado</button><button onClick={()=>conversa('cobrar')} className="ui-btn-secondary justify-start"><Gauge size={15}/> Cobrar resultado</button><button onClick={()=>conversa('prestigiar')} className="ui-btn-secondary justify-start"><Crown size={15}/> Prestigiar publicamente · 2 CP</button></div><p className="mt-3 text-[11px] leading-relaxed text-muted">Essas conversas também estão disponíveis pelo Telefone Presidencial, visível no canto inferior da tela.</p></div>
              <div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="mb-2 flex items-center gap-2"><Phone size={15} className="text-info"/><h3 className="text-sm font-black text-text">Linha direta</h3></div><p className="text-xs leading-relaxed text-muted">Quando esta pasta gerar uma urgência, o ministro pode ligar enquanto você estiver no Congresso, Economia ou qualquer outra área do jogo.</p></div>
              <div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="text-xs font-black text-text">Prioridade presidencial</div><div className="mt-3 grid grid-cols-3 gap-1">{['baixa','normal','alta'].map(p=><button key={p} onClick={()=>definirPrioridade(cargo.id,p)} className={`rounded-lg border px-2 py-2 text-[10px] font-black uppercase ${cargo.prioridade===p?'border-primary bg-primary/10 text-text':'border-border text-muted'}`}>{p}</button>)}</div></div>
              <button onClick={()=>{if(window.confirm('Forçar intervenção presidencial nesta pasta?')) intervirMinisterio(cargo.id)}} className="ui-btn-secondary w-full justify-center hover:border-danger hover:text-danger">Intervenção direta · 6 CP</button>
            </aside>
          </div>}</>}

          {tab==='operacoes'&&<div><div className="mb-5 flex items-end justify-between gap-4"><div><div className="ui-kicker">Casos presidenciais · {cargo.nome}</div><h2 className="text-2xl font-black text-text">Mesa de Operações</h2><p className="mt-1 text-sm text-muted">Diagnóstico, priorização, montagem de pacotes e sequências de resposta. Sem reflexo: o desafio é ler o problema.</p></div><BrainCircuit size={30} className="text-info"/></div>{desafios.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{desafios.map(d=><button key={d.id} onClick={()=>setDesafio(d)} className="group rounded-2xl border border-border bg-card/70 p-5 text-left hover:border-info/35"><div className="mb-3 flex items-center justify-between"><span className="ui-chip">{d.mecanica||d.tipo}</span><Sparkles size={16} className="text-warning"/></div><h3 className="font-black text-text">{d.titulo}</h3><p className="mt-1 text-sm text-muted">{d.subtitulo}</p><div className="mt-4 text-xs font-bold text-info">Abrir operação →</div></button>)}</div>:<div className="rounded-3xl border border-dashed border-border bg-panel/25 p-10 text-center text-muted">Novos casos desta pasta serão incorporados ao catálogo.</div>}</div>}

          {tab==='eventos'&&<NationalEventsPanel ministerioId={cargo.id}/>} 
        </div>
      </main>
    </div>
    {modalCargo&&<NomeacaoModal cargo={modalCargo} onClose={()=>setModalCargo(null)}/>} {desafio&&<MinistryChallengeModal desafio={desafio} onClose={()=>setDesafio(null)}/>} {conselho&&<CabinetCouncilModal onClose={()=>setConselho(false)}/>} 
  </div>;
}

function InfoCard({icon:Icon,title,text,tone}){return <div className={`rounded-2xl border p-4 ${tone==='warning'?'border-warning/20 bg-warning/5':'border-border bg-panel/45'}`}><div className={`mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-wider ${tone==='warning'?'text-warning':'text-muted'}`}><Icon size={14}/>{title}</div><p className="text-sm leading-relaxed text-text/70">{text}</p></div>}
