import React, { useMemo, useState } from 'react';
import {
  Activity, BookOpen, Building2, ChevronLeft, ChevronRight, CircleDollarSign, Flag, Gavel, Handshake, Landmark,
  Network, ShieldAlert, Target, Users, Vote, WalletCards, UserPlus, Coins, HeartHandshake,
  Gauge, TrendingUp, AlertTriangle, BadgeCheck, MapPinned, Crown, BriefcaseBusiness, Megaphone, ListChecks, Clock3
} from 'lucide-react';
import useGameStore from '../store/useGameStore';
import PartyLogo from './PartyLogo';
import PartyDirectorateMap from './PartyDirectorateMap';
import PoliticalAvatar from './PoliticalAvatar';
import CharacterDossierModal from './CharacterDossier';
import { PARTY_ACTIONS } from '../game/partyEngine.js';
import { toast } from './sonner';

const tone=(n)=>Number(n)>=70?'text-success':Number(n)>=45?'text-warning':'text-danger';
const bgTone=(n)=>Number(n)>=70?'border-success/25 bg-success/5':Number(n)>=45?'border-warning/25 bg-warning/5':'border-danger/25 bg-danger/5';
const fmtMoney=(n)=>`R$ ${Number(n||0).toFixed(1)} mi`;
const fmtInt=(n)=>Number(n||0).toLocaleString('pt-BR');
const Meter=({label,value})=><div><div className="flex items-center justify-between gap-3 text-[10px]"><span className="font-bold text-muted">{label}</span><b className={tone(value)}>{Math.round(value||0)}</b></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-bg"><div className="h-full rounded-full bg-info" style={{width:`${Math.max(2,Math.min(100,value||0))}%`}}/></div></div>;
const Stat=({label,value,detail,Icon=Activity,valueClass='text-text'})=><div className="rounded-2xl border border-border bg-bg/40 p-3"><div className="flex items-center justify-between gap-2"><div className="ui-data-label">{label}</div><Icon size={15} className="text-info"/></div><div className={`mt-2 text-xl font-black ${valueClass}`}>{value}</div>{detail&&<div className="mt-1 text-[9px] leading-relaxed text-muted">{detail}</div>}</div>;

const moodLabel=(p)=>({mobilizado:'Mobilizado','em rebelião':'Em rebelião',fragmentado:'Fragmentado',tenso:'Tenso','estável':'Estável'}[p?.humorInterno]||p?.humorInterno||'Estável');

export default function Parties(){
  const {partidos=[],perfilPresidencial,nomeacoes=[],cargos=[],capitalPolitico,turno,dataString,faseEleitoral,eleicao,sistemaPartidario={},executarAcaoPartidaria,responderCobrancaPartidaria,responderPropostaPartidaria,intervirDiretorioPartidario}=useGameStore();
  const [partyId,setPartyId]=useState(perfilPresidencial?.partidoId||partidos[0]?.id);
  const [tab,setTab]=useState('vida');
  const [uf,setUf]=useState(perfilPresidencial?.ufOrigem||'SP');
  const [person,setPerson]=useState(null);
  const party=partidos.find(p=>p.id===partyId)||partidos[0];
  const dir=party?.diretorios?.find(d=>d.uf===uf)||party?.diretorios?.[0];
  const sortedDirs=useMemo(()=>[...(party?.diretorios||[])].sort((a,b)=>a.nomeEstado.localeCompare(b.nomeEstado,'pt-BR')),[party?.diretorios]);
  const dirIndex=Math.max(0,sortedDirs.findIndex(d=>d.uf===dir?.uf));
  const visibleDirs=sortedDirs.length?Array.from({length:Math.min(2,sortedDirs.length)},(_,i)=>sortedDirs[(dirIndex+i)%sortedDirs.length]):[];
  const stepDir=(delta)=>{if(!sortedDirs.length)return;const next=(dirIndex+delta+sortedDirs.length)%sortedDirs.length;setUf(sortedDirs[next].uf)};
  const own=party?.id===perfilPresidencial?.partidoId;
  const totalSeats=useMemo(()=>partidos.reduce((s,p)=>s+(p.cadeiras||0),0),[partidos]);
  const ministers=useMemo(()=>nomeacoes.filter(n=>(n.partidoId||n.filiacaoPartidaria?.partidoId)===party?.id),[nomeacoes,party?.id]);
  const cargoNome=(id)=>cargos.find(c=>c.id===id)?.nome||id;
  if(!party)return <div className="ui-surface p-6 text-sm text-muted">Catálogo partidário indisponível.</div>;
  const tabs=[['vida','Vida interna'],...(own?[['governo','Partido no poder']]:[]),['movimentos','Janela & alianças'],['identidade','Identidade'],['alas','Alas internas'],['diretorios','Diretórios estaduais'],['governanca','Como o partido decide']];
  const run=(id,args={})=>{const r=executarAcaoPartidaria(id,args);r.ok?toast.success(`${r.partido.sigla}: ${r.texto}`):toast.error(r.motivo)};
  const crises=(party.crisesInternas||[]).filter(c=>!c.resolvida);
  const gov=party.governoPartidario||{};
  const cobrancas=(gov.cobrancas||[]);
  const cobrancasAbertas=cobrancas.filter(c=>['pendente','comprometida','negociada'].includes(c.status));
  const responder=(id,resposta)=>{const r=responderCobrancaPartidaria(id,resposta);r.ok?toast.success(r.texto):toast.error(r.motivo)};
  const statusLabel={pendente:'Aguardando resposta',comprometida:'Compromisso assumido',negociada:'Prazo negociado',cumprida:'Cumprida',descumprida:'Descumprida',recusada:'Recusada',ignorada:'Ignorada'};
  const partyName=(id)=>partidos.find(p=>p.id===id)?.sigla||id;
  const propostas=(sistemaPartidario.propostas||[]).filter(x=>x.partidos?.includes(party.id));
  const propostasPendentes=propostas.filter(x=>x.status==='pendente');
  const aliancas=(sistemaPartidario.aliancas||[]).filter(x=>x.status==='ativa'&&x.partidos?.includes(party.id));
  const migracoes=(sistemaPartidario.migracoes||[]).filter(x=>x.origemId===party.id||x.destinoId===party.id).slice(0,12);
  const intervencoes=(sistemaPartidario.intervencoes||[]).filter(x=>x.partidoId===party.id).slice(0,8);
  const responderAlianca=(id,resposta)=>{const r=responderPropostaPartidaria(id,resposta);r.ok?toast.success(r.texto):toast.error(r.motivo)};
  const intervir=()=>{const r=intervirDiretorioPartidario(dir?.uf);r.ok?toast.success(r.texto):toast.error(r.motivo)};

  return <div className="grid h-full min-h-0 gap-3 xl:grid-cols-[250px_1fr]">
    <aside className="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-border bg-card/65">
      <div className="border-b border-border p-4"><div className="ui-kicker">Sistema partidário</div><h3 className="mt-1 text-lg font-black">Máquinas políticas</h3><p className="mt-1 text-[11px] leading-relaxed text-muted">Direções, alas e diretórios agora mudam com o tempo — e a disciplina chega ao plenário.</p></div>
      <div className="min-h-0 flex-1 space-y-2 overflow-y-auto p-3">{partidos.map(p=>{const active=p.id===party.id;const isOwn=p.id===perfilPresidencial?.partidoId;return <button key={p.id} onClick={()=>{setPartyId(p.id);setUf(perfilPresidencial?.ufOrigem||'SP');if(tab==='governo'&&p.id!==perfilPresidencial?.partidoId)setTab('vida')}} className={`w-full rounded-2xl border p-3 text-left transition ${active?'border-warning/35 bg-warning/5':'border-border bg-panel/35 hover:bg-panel/60'}`}><div className="flex items-center gap-3"><PartyLogo party={p} size={48}/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="text-sm">{p.sigla}</b>{isOwn&&<span className="rounded-md bg-success/10 px-1.5 py-0.5 text-[8px] font-black uppercase text-success">Seu partido</span>}</div><div className="truncate text-[10px] text-muted">{p.nome}</div><div className="mt-1 flex items-center gap-2 text-[9px] font-bold text-muted"><span>{p.cadeiras} dep.</span><span>·</span><span className={tone(p.satisfacaoDirecao)}>{moodLabel(p)}</span></div></div><ChevronRight size={15} className="text-muted"/></div></button>})}</div>
      <div className="border-t border-border p-3"><div className="rounded-xl border border-border bg-bg/45 p-3"><div className="ui-data-label">Câmara mapeada</div><div className="mt-1 text-xl font-black">{totalSeats}<span className="ml-1 text-xs text-muted">cadeiras</span></div></div></div>
    </aside>

    <main className="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-border bg-card/65">
      <header className="shrink-0 border-b border-border bg-panel/45 p-4 md:p-5">
        <div className="flex flex-wrap items-center gap-4"><PartyLogo party={party} size={76}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="ui-kicker">Partido nº {party.numero} · fundado em {party.fundacao}</span>{own&&<span className="ui-chip border-success/25 text-success">partido do Presidente</span>}<span className={`ui-chip ${bgTone(party.satisfacaoDirecao)}`}>{moodLabel(party)}</span></div><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">{party.sigla} · {party.nome}</h2><p className="mt-1 text-xs font-bold text-muted">{party.ideologia} · “{party.slogan}”</p></div><div className="grid grid-cols-3 gap-2 text-center"><div className="rounded-xl border border-border bg-bg/40 px-3 py-2"><div className="ui-data-label">Máquina</div><b className={`text-xl ${tone(party.maquina)}`}>{Math.round(party.maquina||0)}</b></div><div className="rounded-xl border border-border bg-bg/40 px-3 py-2"><div className="ui-data-label">Disciplina</div><b className={`text-xl ${tone(party.disciplina)}`}>{Math.round(party.disciplina||0)}</b></div><div className="rounded-xl border border-border bg-bg/40 px-3 py-2"><div className="ui-data-label">Direção</div><b className={`text-xl ${tone(party.satisfacaoDirecao)}`}>{Math.round(party.satisfacaoDirecao||0)}</b></div></div></div>
        <div className="mt-4 flex gap-1 overflow-x-auto">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-lg border px-3 py-2 text-[10px] font-black uppercase tracking-wider ${tab===id?'border-warning/35 bg-warning/5 text-text':'border-transparent text-muted hover:bg-panel'}`}>{label}</button>)}</div>
      </header>

      <div className="min-h-0 flex-1 overflow-y-auto p-4 md:p-5">
        {tab==='vida'&&<div className="space-y-4">
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
            <Stat label="Satisfação da direção" value={`${Math.round(party.satisfacaoDirecao||0)}%`} detail="Confiança na linha nacional" Icon={HeartHandshake} valueClass={tone(party.satisfacaoDirecao)}/>
            <Stat label="Unidade interna" value={`${Math.round(party.unidadeInterna||0)}%`} detail="Quanto as alas ainda caminham juntas" Icon={Network} valueClass={tone(party.unidadeInterna)}/>
            <Stat label="Caixa partidário" value={fmtMoney(party.caixaPartidario)} detail={`Balanço mensal ${Number(party.balancoFundo?.saldo||0)>=0?'+':''}${Number(party.balancoFundo?.saldo||0).toFixed(1)} mi`} Icon={Coins}/>
            <Stat label="Filiados" value={fmtInt(party.filiadosNacionais)} detail="Soma estimada dos 27 diretórios" Icon={UserPlus}/>
            <Stat label="Prestígio" value={`${Math.round(party.prestigioPartidario||0)}`} detail="Máquina + disciplina + projeção" Icon={TrendingUp} valueClass={tone(party.prestigioPartidario)}/>
          </div>

          <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
            <section className="rounded-2xl border border-border bg-panel/38 p-4">
              <div className="flex items-start justify-between gap-3"><div><div className="ui-kicker">Pulso da máquina</div><h3 className="mt-1 text-xl font-black">O partido também precisa ser governado</h3><p className="mt-1 text-xs leading-relaxed text-muted">Caixa financia estrutura; satisfação sustenta disciplina; disciplina influencia quantos deputados seguem a orientação da bancada.</p></div><Gauge className="text-info"/></div>
              <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Meter label="Militância" value={party.militancia}/><Meter label="Formação de quadros" value={party.formacaoQuadros}/><Meter label="Capilaridade" value={party.capilaridade}/><Meter label="Operação no Congresso" value={party.congresso}/><Meter label="Mobilização digital" value={party.digital}/><Meter label="Prestígio partidário" value={party.prestigioPartidario}/></div>
              <div className="mt-5 grid gap-3 md:grid-cols-2">
                <div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Fundo neste mês</div><div className="mt-2 flex items-center justify-between text-xs"><span className="text-muted">Entrada</span><b className="text-success">+{fmtMoney(party.balancoFundo?.entrada)}</b></div><div className="mt-1 flex items-center justify-between text-xs"><span className="text-muted">Manutenção da máquina</span><b className="text-danger">-{fmtMoney(party.balancoFundo?.saida)}</b></div><div className="mt-2 border-t border-border pt-2 text-xs"><span className="text-muted">Saldo mensal </span><b>{Number(party.balancoFundo?.saldo||0)>=0?'+':''}{fmtMoney(party.balancoFundo?.saldo)}</b></div></div>
                <div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Presença no governo</div><div className="mt-2 text-2xl font-black">{ministers.length}</div><div className="text-[10px] text-muted">ministro(s) filiado(s) atualmente</div>{ministers.slice(0,3).map(m=><div key={m.id} className="mt-2 flex items-center justify-between text-[10px]"><span className="truncate text-muted">{m.nome}</span><span className="font-black">{m.filiacaoPartidaria?.alaId?.replaceAll('_',' ')||'filiado'}</span></div>)}</div>
              </div>
            </section>

            <aside className="space-y-3">
              {own?<div className="rounded-2xl border border-success/20 bg-success/5 p-4"><div className="ui-kicker text-success">Direção do partido do Presidente</div><h3 className="mt-1 text-lg font-black">Ações internas do mês</h3><p className="mt-1 text-xs text-muted">Até duas ações. Algumas gastam Capital Político; todas usam recursos do partido.</p><div className="mt-3 grid gap-2">{['reuniao_executiva','mobilizar_militancia','formacao_quadros'].map(id=>{const a=PARTY_ACTIONS[id];const used=(party.acoesPartidariasTurno||[]).includes(id);return <button key={id} disabled={used} onClick={()=>run(id)} className="rounded-xl border border-border bg-card/50 p-3 text-left disabled:opacity-40"><div className="flex items-center justify-between gap-2"><b className="text-xs">{a.nome}</b><span className="text-[9px] font-black text-warning">{a.custoCapital?`${a.custoCapital} CP · `:''}{fmtMoney(a.custoCaixa)}</span></div><p className="mt-1 text-[10px] leading-relaxed text-muted">{a.descricao}</p><div className="mt-2 text-[9px] font-black uppercase tracking-wider text-info">{a.efeito}</div></button>})}</div><div className="mt-3 text-[10px] text-muted">Capital Político disponível: <b className="text-text">{Math.round(capitalPolitico||0)}</b> · ações usadas {(party.acoesPartidariasTurno||[]).length}/2</div></div>:<div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Partido adversário / independente</div><h3 className="mt-1 text-lg font-black">Você observa, mas não comanda.</h3><p className="mt-2 text-xs leading-relaxed text-muted">A Executiva deste partido toma suas próprias decisões. O Planalto pode influenciar a legenda por coalizão, leis, ministérios, governadores e eleições — não por controle direto da máquina.</p></div>}
              {crises.length?<div className="rounded-2xl border border-danger/25 bg-danger/5 p-4"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-danger"/><div className="ui-kicker text-danger">Crises internas</div></div><div className="mt-3 space-y-2">{crises.slice(0,4).map(c=><div key={c.id} className="rounded-xl border border-danger/20 bg-bg/30 p-3"><div className="text-xs font-black">{c.titulo}</div><p className="mt-1 text-[10px] leading-relaxed text-muted">{c.texto}</p><div className="mt-2 text-[9px] font-black uppercase text-danger">gravidade {c.gravidade}/100</div></div>)}</div></div>:<div className="rounded-2xl border border-success/20 bg-success/5 p-4"><div className="flex items-center gap-2"><BadgeCheck size={16} className="text-success"/><div className="ui-kicker text-success">Sem crise interna aberta</div></div><p className="mt-2 text-xs text-muted">Há disputas normais entre correntes e diretórios, mas nenhuma rompeu o limite de crise neste momento.</p></div>}
            </aside>
          </div>

          <div className="rounded-2xl border border-border bg-panel/30 p-4"><div className="ui-kicker">Histórico recente</div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{(party.historicoPartidario||[]).slice(0,8).map((h,i)=><div key={`${h.turno}_${i}`} className="rounded-xl border border-border bg-bg/35 p-3"><div className="text-[9px] font-black uppercase text-info">Turno {h.turno}</div><div className="mt-1 text-xs font-black">{h.tipo==='acao'?h.texto:`${h.humor||'movimento interno'}`}</div>{h.tipo!=='acao'&&<div className="mt-1 text-[9px] text-muted">direção {Math.round(h.satisfacao||0)} · unidade {Math.round(h.unidade||0)} · disciplina {Math.round(h.disciplina||0)}</div>}</div>)}{!party.historicoPartidario?.length&&<div className="text-xs text-muted">A história interna começa a ser registrada na primeira virada mensal.</div>}</div></div>
        </div>}

        {tab==='governo'&&own&&<div className="space-y-4">
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
            <Stat label="Relação com o Presidente" value={`${Math.round(gov.relacaoPresidente||0)}%`} detail="Confiança da Executiva no Planalto" Icon={HeartHandshake} valueClass={tone(gov.relacaoPresidente)}/>
            <Stat label="Coerência programática" value={`${Math.round(gov.coerenciaProgramatica||0)}%`} detail="Quanto o governo ainda parece com o programa da legenda" Icon={ListChecks} valueClass={tone(gov.coerenciaProgramatica)}/>
            <Stat label="Espaço ministerial" value={`${Math.round(gov.espacoMinisterial||0)}%`} detail={`${gov.ministrosPartido||0}/${gov.metaMinistros||0} ministro(s) esperados`} Icon={BriefcaseBusiness} valueClass={tone(gov.espacoMinisterial)}/>
            <Stat label="Núcleo estratégico" value={`${Math.round(gov.espacoEstrategico||0)}%`} detail={`${gov.ministrosEstrategicos||0} pasta(s) estratégica(s)`} Icon={Crown} valueClass={tone(gov.espacoEstrategico)}/>
            <Stat label="Compromissos cumpridos" value={`${Math.round(gov.indiceAtendimento||0)}%`} detail={`${gov.cumpridas||0} entregues · ${gov.descumpridas||0} frustrados`} Icon={BadgeCheck} valueClass={tone(gov.indiceAtendimento)}/>
          </div>

          <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
            <section className="space-y-4">
              <div className="rounded-2xl border border-border bg-panel/38 p-4">
                <div className="flex items-start justify-between gap-3"><div><div className="ui-kicker">Executiva Nacional → Palácio do Planalto</div><h3 className="mt-1 text-xl font-black">Seu partido também governa — e cobra.</h3><p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted">Apoio eleitoral não é cheque em branco. Cargos, agenda, bandeiras e coerência afetam disciplina, apoio da bancada e a relação com a direção partidária.</p></div><Megaphone className="text-warning"/></div>
                <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Cobranças abertas</div><div className="mt-1 text-2xl font-black">{cobrancasAbertas.length}</div></div><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Apoio da bancada</div><div className={`mt-1 text-2xl font-black ${tone(party.apoio)}`}>{Math.round(party.apoio||0)}%</div></div><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Capital político</div><div className={`mt-1 text-2xl font-black ${tone(capitalPolitico)}`}>{Math.round(capitalPolitico||0)}</div></div></div>
              </div>

              <div className="rounded-2xl border border-border bg-panel/30 p-4">
                <div className="flex items-center justify-between gap-3"><div><div className="ui-kicker">Cobranças da Executiva</div><h3 className="mt-1 font-black">O que a legenda espera do governo</h3></div><span className="ui-chip">{cobrancasAbertas.length} em curso</span></div>
                <div className="mt-4 space-y-3">{cobrancas.length===0&&<div className="rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted">Nenhuma cobrança formal foi apresentada ainda. A direção acompanha composição do gabinete, agenda, leis e coerência do governo.</div>}{cobrancas.slice(0,10).map(c=>{const active=['pendente','comprometida','negociada'].includes(c.status);const bad=['descumprida','recusada','ignorada'].includes(c.status);return <article key={c.id} className={`rounded-2xl border p-4 ${bad?'border-danger/25 bg-danger/5':active?'border-warning/25 bg-warning/5':'border-success/20 bg-success/5'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="ui-data-label">{c.tipo}</span><span className={`ui-chip ${bad?'border-danger/25 text-danger':c.status==='cumprida'?'border-success/25 text-success':'border-warning/25 text-warning'}`}>{statusLabel[c.status]||c.status}</span></div><h4 className="mt-2 font-black">{c.titulo}</h4><p className="mt-1 text-xs leading-relaxed text-muted">{c.texto}</p><div className="mt-3 rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Pedido</div><p className="mt-1 text-xs font-bold text-text/85">{c.pedido}</p></div></div><div className="min-w-[150px] text-right text-[10px] text-muted"><div>{c.portaVoz}</div>{c.status==='pendente'&&<div className="mt-1 flex items-center justify-end gap-1 text-warning"><Clock3 size={12}/> responder até mês {c.responderAte}</div>}{['comprometida','negociada'].includes(c.status)&&<div className="mt-1 flex items-center justify-end gap-1 text-info"><Clock3 size={12}/> entregar até mês {c.prazoCumprimento}</div>}{c.resolvidaNoTurno&&<div className="mt-1">resolvida no mês {c.resolvidaNoTurno}</div>}</div></div>{c.status==='pendente'&&<div className="mt-4 grid gap-2 sm:grid-cols-3"><button onClick={()=>responder(c.id,'comprometer')} className="ui-btn-primary justify-center">Assumir · {c.custoCapital||1} CP</button><button onClick={()=>responder(c.id,'negociar')} className="ui-btn-secondary justify-center">Negociar prazo · 2 CP</button><button onClick={()=>responder(c.id,'recusar')} className="ui-btn-secondary justify-center border-danger/25 text-danger">Recusar</button></div>}{c.resposta&&<p className="mt-3 text-[10px] font-bold text-muted">{c.resposta}</p>}{c.desfecho&&<p className="mt-2 text-[10px] text-muted">{c.desfecho}</p>}</article>})}</div>
              </div>
            </section>

            <aside className="space-y-4">
              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Presença no governo</div><h3 className="mt-1 font-black">Quem do {party.sigla} está no primeiro escalão</h3><div className="mt-3 space-y-2">{ministers.length?ministers.map(m=><div key={m.id} className="rounded-xl border border-border bg-bg/35 p-3"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-black">{m.nome}</div><div className="text-[9px] text-muted">{m.cargo||m.cargoNome||cargoNome(m.cargoId)}</div></div><span className="ui-chip">{(gov.pastasEstrategicas||[]).includes(m.cargoId)?'núcleo estratégico':'gabinete'}</span></div></div>):<div className="rounded-xl border border-dashed border-border p-4 text-xs text-muted">Nenhum ministro filiado ao partido presidencial.</div>}</div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Meta da Executiva</div><div className="mt-1 text-xl font-black">{gov.metaMinistros||0}</div></div><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Hoje</div><div className="mt-1 text-xl font-black">{gov.ministrosPartido||0}</div></div></div></div>

              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Agenda esperada</div><h3 className="mt-1 font-black">Onde a direção quer ver o Presidente</h3><div className="mt-3 flex flex-wrap gap-2">{(gov.agendaPreferencial||[]).map(id=><span key={id} className="ui-chip">{({ruas:'Ruas & sociedade',ciencia:'Ciência & inovação',congresso:'Congresso',governadores:'Governadores',empresas:'Empresas',producao:'Produção',gabinete:'Gabinete',imprensa:'Imprensa'})[id]||id}</span>)}</div><div className="mt-4"><Meter label="Agenda partidária atendida" value={gov.agendaAtendida}/></div></div>

              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Como chegamos à coerência</div><h3 className="mt-1 font-black">O partido compara discurso e governo</h3><p className="mt-1 text-[10px] leading-relaxed text-muted">Posições públicas, promessas, leis recentes e medidas econômicas compõem a leitura da Executiva.</p><div className="mt-3 grid grid-cols-2 gap-2">{[['Posições públicas',gov.coerenciaDetalhes?.eixos||0,55],['Promessas',gov.coerenciaDetalhes?.promessas||0,20],['Legislação recente',gov.coerenciaDetalhes?.legislacao||0,25]].map(([label,value,max])=><div key={label} className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">{label}</div><div className="mt-1 text-lg font-black">{Number(value).toFixed(1)}<span className="ml-1 text-[9px] text-muted">/ {max}</span></div></div>)}<div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Medidas econômicas</div><div className={`mt-1 text-lg font-black ${Number(gov.coerenciaDetalhes?.economia||0)>0?'text-success':Number(gov.coerenciaDetalhes?.economia||0)<0?'text-danger':'text-muted'}`}>{Number(gov.coerenciaDetalhes?.economia||0)>0?'+':''}{Number(gov.coerenciaDetalhes?.economia||0).toFixed(1)}</div></div></div></div>

              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Memória Planalto–partido</div><div className="mt-3 space-y-2">{(gov.historico||[]).slice(0,7).map((h,i)=><div key={`${h.turno}_${i}`} className="rounded-xl border border-border bg-bg/35 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-muted">Mês {h.turno} · {String(h.tipo||'registro').replaceAll('_',' ')}</div><div className="mt-1 text-xs font-bold">{h.titulo||h.texto}</div></div>)}{!(gov.historico||[]).length&&<div className="text-xs text-muted">A relação ainda não produziu marcos próprios.</div>}</div></div>
            </aside>
          </div>
        </div>}

        {tab==='movimentos'&&<div className="space-y-4">
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <Stat label="Janela partidária" value={sistemaPartidario.janela?.ativa?'ABERTA':'Fechada'} detail={sistemaPartidario.janela?.ativa?'05/03 a 03/04/2026 · migrações em alta':`Campanha: ${dataString||faseEleitoral||'mandato'}`} Icon={Vote} valueClass={sistemaPartidario.janela?.ativa?'text-success':'text-muted'}/>
            <Stat label="Alianças ativas" value={aliancas.length} detail="Coordenação nacional que envolve esta legenda" Icon={Handshake}/>
            <Stat label="Migrações recentes" value={migracoes.length} detail="Entradas, saídas e dissidências registradas" Icon={UserPlus}/>
            <Stat label="Intervenções" value={intervencoes.length} detail="Diretórios sob comando extraordinário" Icon={Gavel}/>
          </div>
          <div className="grid gap-4 xl:grid-cols-[1.08fr_.92fr]">
            <section className="space-y-4">
              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="flex items-start justify-between gap-3"><div><div className="ui-kicker">Negociação entre Executivas</div><h3 className="mt-1 text-xl font-black">Alianças e federações</h3><p className="mt-1 text-xs leading-relaxed text-muted">Alianças coordenam pauta e palanque. Federações são mais duradouras e chegarão à expansão eleitoral com peso sobre convenção, recursos e candidaturas.</p></div><Handshake className="text-info"/></div>
                <div className="mt-4 space-y-2">{propostasPendentes.length?propostasPendentes.map(pr=>{const other=pr.partidos.find(id=>id!==party.id);return <div key={pr.id} className="rounded-2xl border border-warning/25 bg-warning/5 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-sm font-black">{pr.titulo}</div><div className="mt-1 text-[10px] text-muted">compatibilidade {Math.round(pr.compatibilidade||0)}/100 · resposta até o turno {pr.responderAte}</div></div><span className="ui-chip border-warning/25 text-warning">{pr.tipo==='federacao'?'Federação':'Aliança'}</span></div><p className="mt-3 text-xs leading-relaxed text-text/75">{pr.texto}</p>{own&&<div className="mt-3 flex gap-2"><button onClick={()=>responderAlianca(pr.id,'aceitar')} className="ui-btn-primary flex-1 justify-center">Aceitar com {partyName(other)}</button><button onClick={()=>responderAlianca(pr.id,'recusar')} className="ui-btn-secondary flex-1 justify-center">Recusar</button></div>}</div>}):<div className="rounded-xl border border-dashed border-border p-4 text-xs text-muted">Nenhuma proposta pendente envolvendo {party.sigla}.</div>}</div>
                <div className="mt-4 grid gap-2 sm:grid-cols-2">{aliancas.map(a=><div key={a.id} className="rounded-xl border border-success/20 bg-success/5 p-3"><div className="ui-data-label text-success">{a.tipo==='federacao'?'Federação ativa':'Aliança ativa'}</div><div className="mt-1 text-sm font-black">{a.partidos.map(partyName).join(' + ')}</div><div className="mt-1 text-[9px] text-muted">desde o turno {a.inicioTurno} · origem {a.origem}</div></div>)}{!aliancas.length&&<div className="col-span-full rounded-xl border border-dashed border-border p-3 text-xs text-muted">A legenda ainda não possui composição nacional ativa.</div>}</div>
              </div>
              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Troca de legenda</div><h3 className="mt-1 text-lg font-black">Janela, dissidências e filiações</h3><div className="mt-3 space-y-2">{migracoes.map(m=><div key={m.id} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-bg/35 p-3"><div><div className="text-xs font-black">{m.nome}</div><div className="mt-1 text-[9px] text-muted">{partyName(m.origemId)} → {partyName(m.destinoId)} · {m.tipo.replaceAll('_',' ')}</div></div>{m.cadeiras>1?<span className="ui-chip border-warning/25 text-warning">+{m.cadeiras} cadeiras</span>:<span className="ui-chip">turno {m.turno}</span>}</div>)}{!migracoes.length&&<div className="rounded-xl border border-dashed border-border p-3 text-xs text-muted">Nenhuma migração envolvendo esta legenda foi registrada ainda.</div>}</div></div>
            </section>
            <aside className="space-y-4"><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="flex items-start justify-between gap-3"><div><div className="ui-kicker">Comando estadual</div><h3 className="mt-1 text-lg font-black">Intervenção no {party.sigla}-{dir?.uf}</h3></div><Gavel className={(dir?.riscoIntervencao||0)>=70?'text-danger':'text-muted'}/></div><p className="mt-2 text-xs leading-relaxed text-muted">A Executiva pode substituir temporariamente o comando estadual quando autonomia, ruptura e desobediência ameaçam candidaturas e alianças. A medida recupera controle formal, mas pode produzir dissidência.</p><div className="mt-4 space-y-3"><Meter label="Risco de intervenção" value={dir?.riscoIntervencao}/><Meter label="Autonomia estadual" value={dir?.autonomia}/><Meter label="Satisfação local" value={dir?.satisfacao}/></div>{own?<button onClick={intervir} disabled={(dir?.riscoIntervencao||0)<58&&dir?.status!=='disputado'} className="ui-btn-primary mt-4 w-full justify-center disabled:cursor-not-allowed disabled:opacity-40"><Gavel size={14}/> Intervir em {party.sigla}-{dir?.uf} · 3 CP + R$ 14 mi</button>:<div className="mt-4 rounded-xl border border-border bg-bg/35 p-3 text-[10px] text-muted">A direção desta legenda decide autonomamente se intervém em seus diretórios.</div>}</div>
              <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Histórico de intervenções</div><div className="mt-3 space-y-2">{intervencoes.map(i=><div key={i.id} className="rounded-xl border border-border bg-bg/35 p-3"><div className="text-xs font-black">{party.sigla}-{i.uf}</div><div className="mt-1 text-[9px] text-muted">turno {i.turno} · {i.resultado.replaceAll('_',' ')}</div></div>)}{!intervencoes.length&&<div className="text-xs text-muted">Nenhuma intervenção registrada.</div>}</div></div>
            </aside>
          </div>
        </div>}

        {tab==='identidade'&&<div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
          <section className="space-y-4"><div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="flex items-center gap-2"><BookOpen size={16} className="text-info"/><div className="ui-kicker">Identidade histórica</div></div><p className="mt-3 text-sm leading-relaxed text-text/80">{party.historia}</p><p className="mt-3 text-xs leading-relaxed text-muted">{party.identidade}</p></div><div className="grid gap-3 md:grid-cols-3"><InfoBlock icon={Users} title="Base social" items={party.baseSocial}/><InfoBlock icon={Target} title="Prioridades" items={party.prioridades}/><InfoBlock icon={ShieldAlert} title="Linhas vermelhas" items={party.linhasVermelhas}/></div><div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Anatomia da máquina</div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Meter label="Militância" value={party.militancia}/><Meter label="Formação de quadros" value={party.formacaoQuadros}/><Meter label="Mobilização digital" value={party.digital}/><Meter label="Capilaridade municipal" value={party.municipios}/><Meter label="Operação no Congresso" value={party.congresso}/><Meter label="Apoio ao Planalto" value={party.apoio}/></div></div></section>
          <aside className="space-y-4"><button onClick={()=>setPerson(party.presidencia)} className="w-full rounded-2xl border border-border bg-panel/45 p-4 text-left hover:border-warning/30"><div className="flex items-center gap-3"><PoliticalAvatar name={party.presidencia.nome} seed={party.presidencia.avatar} imageKey={party.presidencia.avatar} size={72}/><div className="min-w-0"><div className="ui-kicker">Presidência nacional</div><h3 className="mt-1 text-lg font-black">{party.presidencia.nome}</h3><p className="text-[10px] text-muted">{party.presidencia.uf} · influência {party.presidencia.influencia} · ambição {party.presidencia.ambicao}</p></div></div><p className="mt-3 text-xs italic leading-relaxed text-text/75">“{party.presidencia.frase}”</p><div className="mt-3 text-[10px] font-black uppercase tracking-wider text-info">Abrir dossiê da liderança →</div></button><div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="ui-kicker">Executiva nacional</div><div className="mt-3 space-y-2">{party.executivo.map(x=><div key={x.nome} className="flex items-center justify-between gap-3 rounded-xl border border-border bg-bg/35 p-3"><div><div className="text-xs font-black">{x.nome}</div><div className="text-[9px] text-muted">{x.cargo} · {x.uf}</div></div><b className="text-sm text-warning">{x.influencia}</b></div>)}</div></div></aside>
        </div>}

        {tab==='alas'&&<div><div className="max-w-3xl"><div className="ui-kicker">Partido não é bloco monolítico</div><h3 className="mt-1 text-2xl font-black">Correntes que disputam a identidade do {party.sigla}</h3><p className="mt-2 text-sm text-muted">Força define peso interno. Satisfação define cooperação. Mobilização define a capacidade de uma corrente transformar incômodo em disputa.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{party.alas.map(a=><article key={a.id} className="rounded-3xl border border-border bg-panel/38 p-5"><div className="flex items-center justify-between"><Flag size={18} style={{color:party.corPrincipal}}/><span className="font-mono text-2xl font-black">{Number(a.forca||0).toFixed(1)}%</span></div><h4 className="mt-4 text-lg font-black">{a.nome}</h4><p className="mt-2 text-sm leading-relaxed text-text/75">{a.agenda}</p><div className="mt-4 space-y-3"><Meter label="Satisfação" value={a.satisfacao}/><Meter label="Mobilização" value={a.mobilizacao}/><Meter label="Relação com a direção" value={a.relacaoDirecao}/></div><div className="mt-4 rounded-xl border border-warning/20 bg-warning/5 p-3"><div className="flex items-center justify-between"><div className="ui-data-label text-warning">Ponto de tensão</div><span className={`text-[9px] font-black uppercase ${a.tendencia==='crescendo'?'text-success':a.tendencia==='recuando'?'text-danger':'text-muted'}`}>{a.tendencia}</span></div><p className="mt-1 text-xs text-muted">{a.risco}</p></div>{own&&<button onClick={()=>run('apaziguar_ala',{alaId:a.id})} className="ui-btn-secondary mt-3 w-full justify-center text-[10px]">Apaziguar ala · 1 CP + {fmtMoney(PARTY_ACTIONS.apaziguar_ala.custoCaixa)}</button>}</article>)}</div></div>}

        {tab==='diretorios'&&<div className="grid min-h-0 gap-4 xl:grid-cols-[.88fr_1.12fr]">
          <section className="flex min-h-0 flex-col"><div><div className="ui-kicker">Organização territorial</div><h3 className="mt-1 text-xl font-black">27 diretórios estaduais</h3><p className="mt-1 text-xs text-muted">Clique em uma UF no mapa para abrir imediatamente o diretório correspondente.</p></div><div className="mt-3 h-[350px] min-h-[300px] xl:h-[390px]"><PartyDirectorateMap party={party} selected={dir?.uf} onSelect={setUf}/></div></section>
          <section className="flex min-h-0 flex-col gap-3"><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="flex items-start justify-between gap-3"><div><div className="ui-kicker">{dir?.nomeEstado} · {dir?.regiao}</div><h3 className="mt-1 text-xl font-black">Diretório {party.sigla}-{dir?.uf}</h3><p className="mt-1 text-xs text-muted">{dir?.presidente} · {dir?.cargo}</p></div><span className={`ui-chip ${dir?.status==='disputado'?'border-warning/30 text-warning':'border-success/25 text-success'}`}>{dir?.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><Meter label="Máquina estadual" value={dir?.maquina}/><Meter label="Satisfação local" value={dir?.satisfacao}/><Meter label="Autonomia local" value={dir?.autonomia}/><Meter label="Relação com Nacional" value={dir?.relacaoNacional}/></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Delegados</div><div className="mt-1 text-xl font-black">{dir?.delegados}</div><div className="text-[9px] text-muted">~{fmtInt(dir?.filiadosEstimados)} filiados · {Number(dir?.crescimentoFiliados||0)>=0?'+':''}{dir?.crescimentoFiliados||0} no mês</div></div><div className="rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Caixa estadual</div><div className="mt-1 text-xl font-black">{fmtMoney(dir?.caixaLocal)}</div><div className={`text-[9px] ${Number(dir?.riscoIntervencao||0)>=70?'text-danger':'text-muted'}`}>risco de intervenção {Math.round(dir?.riscoIntervencao||0)}%</div></div></div><div className="mt-4 rounded-xl border border-border bg-bg/35 p-3"><div className="ui-data-label">Ala dominante</div><div className="mt-1 text-sm font-black">{dir?.alaDominante}</div><p className="mt-2 text-xs leading-relaxed text-muted">{dir?.observacao}</p></div>{own&&<button onClick={()=>run('fortalecer_diretorio',{uf:dir?.uf})} className="ui-btn-primary mt-4 w-full justify-center"><MapPinned size={14}/> Fortalecer {party.sigla}-{dir?.uf} · 1 CP + {fmtMoney(PARTY_ACTIONS.fortalecer_diretorio.custoCaixa)}</button>}</div>
            <div className="rounded-2xl border border-border bg-panel/30 p-2.5"><div className="mb-2 flex items-center justify-between gap-3 px-1"><div><div className="ui-data-label">Diretórios estaduais</div><div className="text-[9px] text-muted">{dirIndex+1} de {sortedDirs.length} · use as setas ou o mapa</div></div><div className="flex gap-1"><button type="button" onClick={()=>stepDir(-1)} className="ui-btn-secondary min-h-8 px-2.5" aria-label="Diretório anterior"><ChevronLeft size={15}/></button><button type="button" onClick={()=>stepDir(1)} className="ui-btn-secondary min-h-8 px-2.5" aria-label="Próximo diretório"><ChevronRight size={15}/></button></div></div><div className="grid gap-1.5 sm:grid-cols-2">{visibleDirs.map(d=><button key={d.uf} onClick={()=>setUf(d.uf)} className={`flex items-center justify-between rounded-xl border px-3 py-2 text-left ${d.uf===dir?.uf?'border-warning/35 bg-warning/5':'border-border bg-bg/30'}`}><div><div className="text-xs font-black">{d.uf} · {d.nomeEstado}</div><div className="text-[9px] text-muted">{d.alaDominante} · sat. {Math.round(d.satisfacao||0)}</div></div><div className="text-right"><b className={tone(d.maquina)}>{Math.round(d.maquina||0)}</b><div className="text-[8px] uppercase text-muted">máquina</div></div></button>)}</div></div>
          </section>
        </div>}

        {tab==='governanca'&&<div><div className="max-w-3xl"><div className="ui-kicker">Arquitetura eleitoral em operação</div><h3 className="mt-1 text-2xl font-black">Quem controla o partido controla mais do que a sigla.</h3><p className="mt-2 text-sm leading-relaxed text-muted">A máquina viva do partido agora alimenta diretamente convenção, fundo, candidaturas, alianças e palanques no Comando Eleitoral.</p></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(party.governanca||{}).map(([id,g])=>{const Icon={convencao:Vote,fundo:CircleDollarSign,diretorios:Building2,distribuicao:WalletCards,aliancas:Handshake,intervencao:Gavel,candidaturas:Landmark}[id]||Network;return <article key={id} className="rounded-2xl border border-border bg-panel/38 p-4"><div className="flex items-center justify-between"><div className="grid h-9 w-9 place-items-center rounded-xl border border-border bg-bg/45"><Icon size={17} className="text-info"/></div><span className="ui-chip">estrutura pronta</span></div><h4 className="mt-4 font-black">{g.titulo}</h4><p className="mt-2 text-xs leading-relaxed text-muted">{g.texto}</p></article>})}</div>{own&&eleicao?.partidoAtual===party.id&&eleicao?.partidoEleitoral&&<div className="mt-4 grid gap-3 md:grid-cols-4"><Stat label="Delegados" value={eleicao.partidoEleitoral.delegados?.total||0} detail={`${Number(eleicao.partidoEleitoral.delegados?.apoioPct||0).toFixed(1)}% com a candidatura`} Icon={Vote} valueClass={tone(eleicao.partidoEleitoral.delegados?.apoioPct)}/><Stat label="Máquina eleitoral" value={Math.round(eleicao.partidoEleitoral.maquinaEleitoral||0)} detail="Conversão da estrutura partidária" Icon={Gauge} valueClass={tone(eleicao.partidoEleitoral.maquinaEleitoral)}/><Stat label="Cota presidencial" value={`${Number(eleicao.partidoEleitoral.fundo?.distribuicao?.presidencia||0)}%`} detail={fmtMoney(eleicao.partidoEleitoral.fundo?.valores?.presidencia||0)} Icon={WalletCards}/><Stat label="Chapas definidas" value={(eleicao.partidoEleitoral.candidaturasEstaduais||[]).filter(c=>c.status!=='avaliando').length} detail="de 27 diretórios" Icon={MapPinned}/></div>}<div className="mt-4 rounded-2xl border border-warning/20 bg-warning/5 p-4"><div className="ui-kicker text-warning">Máquina partidária</div><p className="mt-2 text-sm leading-relaxed text-text/80">Os números acima não são estáticos. Uma direção desgastada perde disciplina; um diretório forte acumula autonomia; filiações e caixa alteram capacidade operacional. Na 4.9.7.5, esse patrimônio já é convertido em delegados, cota eleitoral, candidaturas estaduais e poder de barganha na convenção.</p></div></div>}
      </div>
    </main>

    {person&&<CharacterDossierModal person={person} onClose={()=>setPerson(null)} eyebrow={`Direção nacional · ${party.sigla}`} subtitle={`${person.cargo} · ${person.uf}`} imageKey={person.avatar} stats={[{label:'Influência',value:person.influencia},{label:'Ambição',value:person.ambicao}]}/>} 
  </div>;
}

function InfoBlock({icon:Icon,title,items=[]}){return <div className="rounded-2xl border border-border bg-panel/38 p-4"><div className="flex items-center gap-2"><Icon size={15} className="text-info"/><div className="ui-kicker">{title}</div></div><ul className="mt-3 space-y-2">{items.map(x=><li key={x} className="text-xs leading-relaxed text-muted">• {x}</li>)}</ul></div>}
