import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Gauge, Landmark, MapPinned, Scale, ShieldCheck, Sparkles, WalletCards, X } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import { regioesPrograma, modelosExecucaoPrograma, fontesPrograma, governancaPrograma } from '../data/seed/programasGovernamentais.js';
import { ritmosRegulamentacao, escalasRegulamentacao } from '../game/regulationEngine.js';
import { toast } from './sonner';

const money=v=>`R$ ${(Number(v||0)/1000).toFixed(1)} bi`;
const steps=['Estratégia','Território','Entrega','Publicação'];

export default function RegulationModal({processo,onClose}){
  const {leisDisponiveis=[],estados=[],turno=1,regulamentacaoLeis={},simularRegulamentacaoLei,regulamentarLei}=useGameStore();
  const lei=leisDisponiveis.find(l=>l.id===processo.leiId);
  const [step,setStep]=useState(0);
  const [form,setForm]=useState({
    programaNome:processo.programaSugerido||`Implementação de ${processo.tituloLei}`,
    ritmo:'equilibrado',escala:'estruturante',territorio:'nacional',ufs:[],modeloExecucao:'federal',fonte:'tesouro',governanca:'padrao',prioridade:'media',
  });
  const sim=useMemo(()=>simularRegulamentacaoLei?.(processo.id,form),[processo.id,form,simularRegulamentacaoLei]);
  if(!lei||!sim)return null;
  const toggleUF=(uf)=>setForm(f=>({...f,ufs:f.ufs.includes(uf)?f.ufs.filter(x=>x!==uf):[...f.ufs,uf]}));
  const toggleRegion=(r)=>setForm(f=>{const all=r.ufs.every(uf=>f.ufs.includes(uf));return {...f,ufs:all?f.ufs.filter(uf=>!r.ufs.includes(uf)):[...new Set([...f.ufs,...r.ufs])]};});
  const canNext=step!==1||form.territorio==='nacional'||form.ufs.length>0;
  const submit=()=>{const r=regulamentarLei?.(processo.id,form);if(!r?.ok)return toast.error(r?.motivo||'Não foi possível publicar a regulamentação.');toast.success(`${lei.titulo} regulamentada. Programa em implantação.`);onClose?.();};
  const urgency=Math.max(0,(processo.prazoNoTurno||0)-turno);
  return <div className="fixed inset-0 z-[155] grid place-items-center bg-black/80 p-2 backdrop-blur-xl md:p-5" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.()}}>
    <section className="flex h-[min(94vh,830px)] w-full max-w-6xl flex-col overflow-hidden rounded-3xl border border-border bg-card shadow-elevation-5">
      <header className="flex shrink-0 items-start justify-between gap-4 border-b border-border bg-panel/85 px-5 py-4"><div><div className="ui-kicker">Casa Civil · regulamentação da lei</div><h2 className="mt-1 text-xl font-black">{lei.titulo}</h2><p className="mt-1 text-xs text-muted">Transforme o texto aprovado em desenho executável. Cada escolha muda custo, risco e capacidade de entrega.</p></div><button onClick={onClose} className="ui-btn-secondary px-3"><X size={17}/></button></header>
      <div className="grid shrink-0 grid-cols-2 gap-2 border-b border-border px-5 py-3 md:grid-cols-4">{steps.map((s,i)=><div key={s} className={`rounded-xl border px-3 py-2 ${i===step?'border-success/40 bg-success/7':i<step?'border-border bg-panel/45':'border-border/60 bg-bg/40'}`}><div className={`text-[9px] font-black uppercase ${i<=step?'text-success':'text-muted'}`}>{i<step?'✓':i+1}</div><div className="mt-0.5 text-[10px] font-black">{s}</div></div>)}</div>
      <main className="min-h-0 flex-1 overflow-y-auto p-5 md:p-6">
        {step===0&&<div className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><section><div className="ui-kicker">Escolha o ritmo político</div><h3 className="mt-1 text-xl font-black">Velocidade também é uma decisão de governo</h3><div className="mt-4 grid gap-2 md:grid-cols-3">{ritmosRegulamentacao.map(x=><Choice key={x.id} active={form.ritmo===x.id} title={x.nome} detail={x.descricao} onClick={()=>setForm({...form,ritmo:x.id})}/>)}</div><div className="ui-kicker mt-6">Escala inicial</div><div className="mt-3 grid gap-2 md:grid-cols-3">{escalasRegulamentacao.map(x=><Choice key={x.id} active={form.escala===x.id} title={x.nome} detail={x.descricao} onClick={()=>setForm({...form,escala:x.id})}/>)}</div></section><aside className="rounded-2xl border border-border bg-panel/42 p-4"><div className="ui-kicker">Pressão do relógio</div><div className="mt-2 text-3xl font-black">{processo.mesesEmAtraso>0?`${processo.mesesEmAtraso}m atrasada`:urgency>0?`${urgency}m`:'prazo final'}</div><p className="mt-1 text-xs text-muted">Prazo político definido pelo grau de complexidade da lei. Atrasos aumentam o risco de inércia, controle e desgaste.</p><div className="mt-5 rounded-xl border border-border bg-bg/40 p-3"><div className="text-[10px] font-black uppercase text-muted">Etapas normativas previstas</div><div className="mt-2 space-y-1.5">{(processo.etapasNormativas||[]).map((x,i)=><div key={x} className="flex gap-2 text-xs"><span className="font-mono text-warning">0{i+1}</span><span>{x}</span></div>)}</div></div></aside></div>}

        {step===1&&<div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl border border-border bg-panel/42 p-4"><div className="ui-kicker">Território da implementação</div><h3 className="mt-1 text-xl font-black">Onde a lei vira política pública primeiro?</h3><div className="mt-4 grid grid-cols-2 gap-2"><Choice active={form.territorio==='nacional'} title="Cobertura nacional" detail="A regulamentação nasce para todo o país." onClick={()=>setForm({...form,territorio:'nacional',ufs:[]})}/><Choice active={form.territorio==='estados'} title="Implantação territorial" detail="Escolha estados e expanda depois." onClick={()=>setForm({...form,territorio:'estados'})}/></div><div className="mt-5 rounded-xl border border-border bg-bg/40 p-3 text-xs text-muted"><MapPinned size={15} className="mb-2 text-info"/>Escala territorial afeta custo federal e coordenação com governadores. Uma política focalizada pode ser mais eficiente, mas deixa regiões de fora.</div></section><section className="rounded-2xl border border-border bg-panel/42 p-4">{form.territorio==='nacional'?<div className="grid min-h-[300px] place-items-center rounded-2xl border border-success/20 bg-success/5 text-center"><div><div className="text-5xl">🇧🇷</div><div className="mt-3 font-black">Implantação nacional</div><p className="mt-1 max-w-sm text-xs text-muted">Todos os estados entram no desenho inicial. Relações federativas influenciarão a execução.</p></div></div>:<><div className="flex items-center justify-between"><div><div className="ui-kicker">Carteira territorial</div><h4 className="font-black">Selecione as UFs</h4></div><span className="ui-chip">{form.ufs.length}/27</span></div><div className="mt-3 flex flex-wrap gap-1.5">{regioesPrograma.map(r=><button key={r.id} onClick={()=>toggleRegion(r)} className={`ui-chip ${r.ufs.every(uf=>form.ufs.includes(uf))?'border-info/40 text-info':''}`}>{r.nome}</button>)}</div><div className="mt-4 grid grid-cols-7 gap-1.5">{estados.map(e=><button key={e.uf} onClick={()=>toggleUF(e.uf)} title={e.nome} className={`rounded-lg border py-2 text-[10px] font-black ${form.ufs.includes(e.uf)?'border-success/45 bg-success/8 text-success':'border-border bg-bg/40 text-muted'}`}>{e.uf}</button>)}</div></>}</section></div>}

        {step===2&&<div className="grid gap-3 xl:grid-cols-3"><OptionList title="Modelo de execução" icon={Landmark} items={modelosExecucaoPrograma} value={form.modeloExecucao} onChange={v=>setForm({...form,modeloExecucao:v})}/><OptionList title="Financiamento" icon={WalletCards} items={fontesPrograma} value={form.fonte} onChange={v=>setForm({...form,fonte:v})}/><OptionList title="Governança" icon={ShieldCheck} items={governancaPrograma} value={form.governanca} onChange={v=>setForm({...form,governanca:v})}/></div>}

        {step===3&&<div className="grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><section className="rounded-2xl border border-border bg-panel/42 p-5"><div className="ui-kicker">Programa derivado</div><label className="mt-3 block text-[10px] font-black uppercase text-muted">Nome de implementação</label><input value={form.programaNome} onChange={e=>setForm({...form,programaNome:e.target.value.slice(0,80)})} className="mt-1 w-full rounded-xl border border-border bg-bg px-3 py-2.5 text-sm outline-none focus:border-success/45"/><div className="mt-5 grid grid-cols-2 gap-2"><Kpi label="Custo federal/mês" value={money(sim.custoMensal)} icon={Landmark}/><Kpi label="Duração estimada" value={`${sim.duracao} meses`} icon={Gauge}/><Kpi label="Capital político" value={`${sim.custoCapital} CP`} icon={Scale}/><Kpi label="Capacidade normativa" value={`${sim.custoCapacidade} pt`} icon={Sparkles}/></div><div className="mt-5 ui-kicker">Prioridade na carteira</div><div className="mt-2 grid grid-cols-3 gap-1">{['baixa','media','alta'].map(x=><button key={x} onClick={()=>setForm({...form,prioridade:x})} className={`rounded-lg border py-2 text-[10px] font-black uppercase ${form.prioridade===x?'border-warning/45 bg-warning/8 text-warning':'border-border text-muted'}`}>{x}</button>)}</div></section><aside className="rounded-2xl border border-border bg-panel/42 p-5"><div className="flex items-center justify-between"><div><div className="ui-kicker">Placar do desenho</div><h3 className="mt-1 text-xl font-black">Qualidade regulatória</h3></div><div className={`text-4xl font-black ${sim.nota>=75?'text-success':sim.nota>=55?'text-warning':'text-danger'}`}>{sim.nota}</div></div><div className="mt-5 space-y-4"><Meter label="Capacidade de entrega" value={sim.eficiencia}/><Meter label="Risco de implementação" value={sim.risco} danger/><Meter label="Presença ministerial" value={sim.capacidadeMinisterial*100}/><Meter label="Apoio federativo" value={sim.relacao}/></div><div className="mt-5 rounded-xl border border-warning/20 bg-warning/5 p-3 text-xs text-muted"><b className="text-warning">Capacidade disponível: {regulamentacaoLeis.capacidadeRestante}/{regulamentacaoLeis.capacidadeMax}</b><br/>Leis complexas ocupam mais capacidade normativa. A Casa Civil e a Justiça podem ampliar o limite mensal.</div></aside></div>}
      </main>
      <footer className="flex shrink-0 items-center justify-between border-t border-border bg-panel/65 px-5 py-3"><button onClick={()=>step===0?onClose?.():setStep(s=>s-1)} className="ui-btn-secondary"><ArrowLeft size={15}/>{step===0?'Cancelar':'Voltar'}</button><span className="text-[10px] text-muted">{step+1} de {steps.length}</span>{step<3?<button disabled={!canNext} onClick={()=>setStep(s=>s+1)} className="ui-btn-primary">Próximo <ArrowRight size={15}/></button>:<button onClick={submit} className="ui-btn-primary"><Check size={15}/> Publicar regulamentação</button>}</footer>
    </section>
  </div>;
}

function Choice({active,title,detail,onClick}){return <button onClick={onClick} className={`rounded-2xl border p-4 text-left ${active?'border-success/45 bg-success/7':'border-border bg-panel/35 hover:border-info/30'}`}><div className="flex items-start justify-between gap-2"><div className="text-sm font-black">{title}</div>{active&&<Check size={15} className="text-success"/>}</div><p className="mt-2 text-[10px] leading-relaxed text-muted">{detail}</p></button>}
function OptionList({title,icon:Icon,items,value,onChange}){return <section className="rounded-2xl border border-border bg-panel/42 p-4"><div className="flex items-center gap-2"><Icon size={16} className="text-info"/><div className="font-black">{title}</div></div><div className="mt-3 space-y-2">{items.map(x=><button key={x.id} onClick={()=>onChange(x.id)} className={`w-full rounded-xl border p-3 text-left ${value===x.id?'border-success/45 bg-success/7':'border-border bg-bg/35 hover:border-info/25'}`}><div className="text-xs font-black">{x.nome}</div><p className="mt-1 text-[10px] leading-relaxed text-muted">{x.descricao}</p></button>)}</div></section>}
function Kpi({label,value,icon:Icon}){return <div className="rounded-xl border border-border bg-bg/45 p-3"><Icon size={15} className="text-info"/><div className="mt-2 text-[9px] uppercase text-muted">{label}</div><div className="mt-1 text-sm font-black">{value}</div></div>}
function Meter({label,value,danger=false}){const v=Math.max(0,Math.min(100,Number(value||0)));return <div><div className="flex justify-between text-[10px] font-black"><span>{label}</span><span>{Math.round(v)}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-bg"><div className={`h-full ${danger?(v>60?'bg-danger':v>35?'bg-warning':'bg-success'):(v>70?'bg-success':v>45?'bg-info':'bg-warning')}`} style={{width:`${v}%`}}/></div></div>}
