import React, { useMemo, useState } from 'react';
import { Atom, Rocket, Cpu, TrainFront, Gem, Dna, Satellite, Sparkles, MapPin, Globe2 } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import { toast } from './sonner';

const ICONS={nuclear_2040:Atom,terras_raras:Gem,semicondutores:Cpu,bio_vacinas:Dna,ia_brasil:Cpu,ferrovia_integracao:TrainFront,espacial:Rocket,amazonia_sat:Satellite};
const money=v=>`R$ ${(v/1000).toFixed(1)} bi`;
export default function SpecialProjects(){
  const {catalogoProjetosEspeciais=[],projetosEspeciais=[],estados=[],iniciarProjetoEspecial}=useGameStore();
  const [id,setId]=useState(catalogoProjetosEspeciais[0]?.id); const [uf,setUf]=useState(null);
  const projeto=catalogoProjetosEspeciais.find(p=>p.id===id)||catalogoProjetosEspeciais[0];
  const ativo=projetosEspeciais.find(p=>p.id===projeto?.id&&p.status==='ativo');
  const destino=uf||projeto?.estadoSugerido;
  const andamento=useMemo(()=>projetosEspeciais.filter(p=>p.status==='ativo'),[projetosEspeciais]);
  if(!projeto)return null;
  const iniciar=()=>{const r=iniciarProjetoEspecial(projeto.id,destino);r.ok?toast.success('Projeto estratégico lançado.'):toast.error(r.motivo);};
  return <div className="ui-page h-full min-h-0 overflow-hidden"><div className="grid h-full min-h-0 gap-4 xl:grid-cols-[.72fr_1.28fr]">
    <section className="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-border bg-card/65"><div className="border-b border-border p-4"><div className="ui-kicker">Legado presidencial</div><h2 className="mt-1 text-lg font-black">Projetos Especiais</h2><p className="mt-1 text-xs text-muted">Projetos multianuais que mudam economia, estados e a posição do Brasil no mundo.</p></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{catalogoProjetosEspeciais.map(p=>{const Icon=ICONS[p.id]||Sparkles;const a=projetosEspeciais.find(x=>x.id===p.id&&x.status==='ativo');return <button key={p.id} onClick={()=>{setId(p.id);setUf(null)}} className={`mb-1 flex w-full items-center gap-3 rounded-xl border p-3 text-left ${p.id===projeto.id?'border-success/35 bg-success/5':'border-transparent hover:border-border hover:bg-panel/50'}`}><div className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-panel"><Icon size={18} className="text-success"/></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{p.titulo}</div><div className="mt-0.5 text-[10px] text-muted">{p.area} · {p.duracao} meses</div></div>{a&&<span className="ui-chip text-warning">{a.progresso}%</span>}</button>})}</div><div className="border-t border-border p-3 text-[10px] text-muted">{andamento.length} projeto(s) estratégico(s) em execução</div></section>
    <section className="min-h-0 overflow-hidden rounded-2xl border border-border bg-card/65 p-5"><div className="grid h-full min-h-0 gap-5 lg:grid-cols-[1.12fr_.88fr]"><div className="min-h-0"><div className="flex items-start justify-between gap-4"><div><div className="ui-kicker">{projeto.area}</div><h2 className="mt-1 text-3xl font-black tracking-[-.04em]">{projeto.titulo}</h2></div><div className="rounded-2xl border border-warning/25 bg-warning/5 px-4 py-3 text-right"><div className="ui-data-label">Custo mensal</div><div className="text-xl font-black text-warning">{money(projeto.custoMensal)}</div></div></div><p className="mt-5 text-base leading-relaxed text-text/75">{projeto.descricao}</p>
      <div className="mt-6 grid grid-cols-3 gap-3"><div className="ui-stat"><div className="ui-data-label">Horizonte</div><div className="mt-1 text-xl font-black">{projeto.duracao} meses</div></div><div className="ui-stat"><div className="ui-data-label">Investimento</div><div className="mt-1 text-xl font-black">{money(projeto.investimento)}</div></div><div className="ui-stat"><div className="ui-data-label">PIB potencial</div><div className="mt-1 text-xl font-black text-success">+{projeto.impacto.pib} p.p.</div></div></div>
      {ativo?<div className="mt-6 rounded-2xl border border-success/30 bg-success/5 p-5"><div className="flex items-center justify-between"><div><div className="ui-kicker text-success">Em execução · {ativo.estado}</div><div className="mt-1 text-lg font-black">{ativo.mesesRestantes} meses restantes</div></div><b className="text-2xl text-success">{ativo.progresso}%</b></div><div className="mt-4 h-2 rounded bg-bg"><div className="h-full rounded bg-success" style={{width:`${ativo.progresso}%`}}/></div></div>:<div className="mt-6 rounded-2xl border border-border bg-panel/40 p-5"><div className="ui-kicker">Implantação federativa</div><div className="mt-3 flex gap-3"><select value={destino} onChange={e=>setUf(e.target.value)} className="min-h-11 flex-1 rounded-xl border border-border bg-bg px-3 text-sm text-text">{estados.map(e=><option key={e.uf} value={e.uf}>{e.uf} · {e.nome}</option>)}</select><button onClick={iniciar} className="ui-btn-primary">Lançar projeto</button></div><p className="mt-3 text-xs text-muted">O custo entra na despesa primária mês a mês; o retorno depende de execução, ministérios e crescimento.</p></div>}
    </div><aside className="space-y-4"><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="flex items-center gap-2 text-info"><Globe2 size={17}/><div className="ui-kicker text-info">Gancho para Geopolítica 4.3</div></div><p className="mt-3 text-sm leading-relaxed text-text/75">{projeto.ganchoGeopolitica}</p></div><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="flex items-center gap-2"><MapPin size={17} className="text-warning"/><h3 className="text-sm font-black">Ministérios envolvidos</h3></div><div className="mt-3 flex flex-wrap gap-2">{projeto.ministerios.map(m=><span key={m} className="ui-chip">{m.replace('m_','').replaceAll('_',' ')}</span>)}</div></div><div className="rounded-2xl border border-border bg-panel/45 p-4"><div className="ui-kicker">Risco de execução</div><div className="mt-2 text-3xl font-black text-warning">{projeto.impacto.risco}%</div><p className="mt-2 text-xs text-muted">Pode aumentar com crise fiscal, conflito ministerial ou dependência externa.</p></div></aside></div></section>
  </div></div>;
}
