import React, { useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Globe2, Handshake, Percent, Ship, TrendingUp, AlertTriangle, ChevronRight } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import GameIcon from './GameIcon';
import { toast } from './sonner';

const fmt=v=>`US$ ${(Number(v||0)/1000).toFixed(1)} bi`;
const tone=v=>v>=0?'text-success':'text-danger';
export default function TradeCenter(){
  const {comercioExterior={},paises=[],ajustarTarifaComercial,estimularExportacao,aceitarOportunidadeComercial}=useGameStore();
  const [view,setView]=useState('visao');
  const exp=Object.entries(comercioExterior.exportacoesPorSetor||{});
  const imp=Object.entries(comercioExterior.importacoesPorSetor||{});
  const parceiros=Object.entries(comercioExterior.parceiros||{}).sort((a,b)=>(b[1].exportacoes+b[1].importacoes)-(a[1].exportacoes+a[1].importacoes));
  const oportunidades=comercioExterior.oportunidades||[];
  const doTariff=(setor,d)=>{const r=ajustarTarifaComercial(setor,d);r.ok?toast.success(`${r.item.nome}: tarifa ${r.item.tarifa.toFixed(0)}%.`):toast.error(r.motivo)};
  const doExport=setor=>{const r=estimularExportacao(setor);r.ok?toast.success(`Crédito exportador direcionado a ${r.setor.nome}.`):toast.error(r.motivo)};
  const accept=id=>{const r=aceitarOportunidadeComercial(id);r.ok?toast.success('Oportunidade comercial convertida em acordo.'):toast.error(r.motivo)};
  return <div className="flex h-full min-h-0 flex-col"><div className="mb-3 flex shrink-0 items-center justify-between gap-3"><div className="ui-tabs">{[['visao','Balança'],['exportacoes','Exportações'],['importacoes','Importações'],['mercados','Mercados']].map(([id,l])=><button key={id} onClick={()=>setView(id)} className={`ui-tab ${view===id?'ui-tab-active':''}`}>{l}</button>)}</div><div className={`text-lg font-black ${tone((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))}`}>Saldo {fmt((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))}</div></div>
    {view==='visao'&&<div className="grid min-h-0 flex-1 gap-3 xl:grid-cols-[.9fr_1.1fr]"><section className="grid content-start grid-cols-2 gap-3"><Card icon={ArrowUpFromLine} label="Exportações / mês" value={fmt(comercioExterior.exportacoesMensais)} tone="success"/><Card icon={ArrowDownToLine} label="Importações / mês" value={fmt(comercioExterior.importacoesMensais)} tone="warning"/><Card icon={TrendingUp} label="Balança comercial" value={fmt((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))} tone={(comercioExterior.exportacoesMensais||0)>=(comercioExterior.importacoesMensais||0)?'success':'danger'}/><Card icon={Handshake} label="Acordos ativos" value={String((comercioExterior.acordos||[]).length)} tone="info"/><div className="col-span-2 rounded-2xl border border-border bg-panel/40 p-4"><div className="ui-kicker">Leitura da Fazenda</div><p className="mt-2 text-xs leading-relaxed text-muted">Câmbio competitivo ajuda exportações, mas encarece importados. Tarifa protege produção local e pode pressionar preços. Visitas presidenciais podem abrir mercado e trazer empresas, mas acordos também criam dependências.</p></div></section><section className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-card/60 p-4"><div className="ui-kicker">Oportunidades abertas</div><div className="mt-3 space-y-2">{oportunidades.map(o=>{const p=paises.find(x=>x.id===o.paisId);return <div key={o.id} className="rounded-2xl border border-border bg-panel/40 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black">{o.titulo}</div><div className="mt-1 text-[10px] text-info">{p?.nome||o.paisId} · {o.tipo.replaceAll('_',' ')}</div></div><span className="ui-chip">{fmt(o.valor)}</span></div><p className="mt-2 text-xs leading-relaxed text-muted">{o.texto}</p><button onClick={()=>accept(o.id)} className="ui-btn-secondary mt-3 text-[10px]"><Handshake size={13}/> Negociar acordo</button></div>})}{!oportunidades.length&&<div className="grid min-h-[240px] place-items-center text-center text-sm text-muted">Nenhuma oportunidade aberta. Visitas de Estado, ExpoAgro e negociações diplomáticas podem criar novas.</div>}</div></section></div>}
    {view==='exportacoes'&&<div className="grid min-h-0 flex-1 content-start gap-2 md:grid-cols-2 xl:grid-cols-3">{exp.map(([id,s])=><div key={id} className="rounded-2xl border border-border bg-card/60 p-4"><div className="flex items-center justify-between"><GameIcon icon={Ship} tone="success" size="sm"/><span className="text-lg font-black text-success">{fmt(s.valor)}</span></div><div className="mt-3 font-black">{s.nome}</div><div className="mt-1 text-[10px] text-muted">Potencial exportador {s.potencial}/100</div><div className="mt-3 h-1.5 rounded-full bg-bg"><div className="h-full rounded-full bg-success" style={{width:`${s.potencial}%`}}/></div><button onClick={()=>doExport(id)} className="ui-btn-secondary mt-4 w-full justify-center text-[10px]">Crédito à exportação</button></div>)}</div>}
    {view==='importacoes'&&<div className="grid min-h-0 flex-1 content-start gap-2 md:grid-cols-2 xl:grid-cols-3">{imp.map(([id,s])=><div key={id} className="rounded-2xl border border-border bg-card/60 p-4"><div className="flex items-center justify-between"><GameIcon icon={ArrowDownToLine} tone={s.dependencia>70?'danger':'warning'} size="sm"/><span className="text-lg font-black">{fmt(s.valor)}</span></div><div className="mt-3 font-black">{s.nome}</div><div className="mt-1 text-[10px] text-muted">Dependência externa {s.dependencia}/100</div><div className="mt-4 flex items-center justify-between rounded-xl border border-border bg-panel/40 p-3"><div><div className="ui-data-label">Tarifa setorial</div><div className="text-xl font-black">{s.tarifa}%</div></div><div className="flex gap-1"><button onClick={()=>doTariff(id,-2)} className="ui-btn-secondary px-3">−</button><button onClick={()=>doTariff(id,2)} className="ui-btn-secondary px-3">+</button></div></div></div>)}</div>}
    {view==='mercados'&&<div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[1fr_.8fr]"><section className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-card/60 p-4"><div className="ui-kicker">Principais parceiros</div><div className="mt-3 space-y-2">{parceiros.map(([id,p])=><div key={id} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 rounded-xl border border-border bg-panel/35 p-3"><div><div className="text-xs font-black">{p.nome}</div><div className="text-[9px] text-muted">Acesso ao mercado {p.acesso}/100</div></div><div className="text-right"><div className="text-[9px] text-muted">EXP</div><b className="text-success">{fmt(p.exportacoes)}</b></div><div className="text-right"><div className="text-[9px] text-muted">IMP</div><b className="text-warning">{fmt(p.importacoes)}</b></div></div>)}</div></section><aside className="rounded-2xl border border-border bg-panel/40 p-4"><AlertTriangle size={18} className="text-warning"/><div className="mt-3 text-lg font-black">Comércio é geopolítica</div><p className="mt-2 text-xs leading-relaxed text-muted">Sanções, crises, visitas de Estado, acordos tecnológicos e relações bilaterais alteram acesso. A próxima fase desse módulo pode incluir barreiras sanitárias, antidumping, cotas e retaliações específicas.</p></aside></div>}
  </div>;
}
function Card({icon:Icon,label,value,tone='info'}){return <div className="rounded-2xl border border-border bg-card/65 p-4"><GameIcon icon={Icon} tone={tone} size="sm"/><div className="mt-3 ui-data-label">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>}
