import React, { useMemo, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, Handshake, Ship, TrendingUp, AlertTriangle, Boxes, ShieldAlert, Network, Gauge } from 'lucide-react';
import useGameStore from '../store/useGameStore';
import GameIcon from './GameIcon';
import { IllustratedAsset } from './VisualAsset';
import { toast } from './sonner';

const fmt=v=>`US$ ${(Number(v||0)/1000).toFixed(1)} bi`;
const tone=v=>v>=0?'text-success':'text-danger';
const flowLabel={exportacao:'Exportação',importacao:'Importação',misto:'Cadeia mista'};
export default function TradeCenter(){
  const {comercioExterior={},paises=[],ajustarTarifaComercial,estimularExportacao,aceitarOportunidadeComercial}=useGameStore();
  const [view,setView]=useState('visao');
  const exp=Object.entries(comercioExterior.exportacoesPorSetor||{});
  const imp=Object.entries(comercioExterior.importacoesPorSetor||{});
  const parceiros=Object.entries(comercioExterior.parceiros||{}).sort((a,b)=>(b[1].exportacoes+b[1].importacoes)-(a[1].exportacoes+a[1].importacoes));
  const oportunidades=comercioExterior.oportunidades||[];
  const items=Object.values(comercioExterior.itensEstrategicos||{});
  const [itemId,setItemId]=useState(items[0]?.id||null);
  const strategic=items.find(i=>i.id===itemId)||items[0];
  const preferences=comercioExterior.concorrenciaGeopolitica?.preferencias||{};
  const tensions=comercioExterior.concorrenciaGeopolitica?.tensoes||[];
  const doTariff=(setor,d)=>{const r=ajustarTarifaComercial(setor,d);r.ok?toast.success(`${r.item.nome}: tarifa ${r.item.tarifa.toFixed(0)}% · -${r.custoPolitico||0} CP.`):toast.error(r.motivo)};
  const doExport=setor=>{const r=estimularExportacao(setor);r.ok?toast.success(`Crédito exportador direcionado a ${r.setor.nome}.`):toast.error(r.motivo)};
  const accept=id=>{const r=aceitarOportunidadeComercial(id);r.ok?toast.success(`Acordo fechado · -${r.custoPolitico||0} CP. Relações comerciais podem reagir.`):toast.error(r.motivo)};
  const partnerName=id=>paises.find(p=>p.id===id)?.nome||comercioExterior.parceiros?.[id]?.nome||id.toUpperCase();
  const dependencyHigh=useMemo(()=>items.filter(i=>(i.dependencia||0)>=80).length,[items]);
  return <div className="flex h-full min-h-0 flex-col"><div className="mb-3 flex shrink-0 items-center justify-between gap-3"><div className="ui-tabs overflow-x-auto">{[['visao','Balança'],['exportacoes','Exportações'],['importacoes','Importações'],['estrategicos','Estratégicos'],['mercados','Mercados']].map(([id,l])=><button key={id} onClick={()=>setView(id)} className={`ui-tab shrink-0 ${view===id?'ui-tab-active':''}`}>{l}</button>)}</div><div className={`text-lg font-black ${tone((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))}`}>Saldo {fmt((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))}</div></div>
    {view==='visao'&&<div className="grid min-h-0 flex-1 gap-3 xl:grid-cols-[.9fr_1.1fr]"><section className="grid content-start grid-cols-2 gap-3"><Card icon={ArrowUpFromLine} label="Exportações / mês" value={fmt(comercioExterior.exportacoesMensais)} tone="success"/><Card icon={ArrowDownToLine} label="Importações / mês" value={fmt(comercioExterior.importacoesMensais)} tone="warning"/><Card icon={TrendingUp} label="Balança comercial" value={fmt((comercioExterior.exportacoesMensais||0)-(comercioExterior.importacoesMensais||0))} tone={(comercioExterior.exportacoesMensais||0)>=(comercioExterior.importacoesMensais||0)?'success':'danger'}/><Card icon={Boxes} label="Dependências críticas" value={String(dependencyHigh)} tone={dependencyHigh>=4?'danger':'warning'}/><div className="col-span-2 rounded-2xl border border-border bg-panel/40 p-4"><div className="ui-kicker">Leitura estratégica</div><p className="mt-2 text-xs leading-relaxed text-muted">A balança agrega setores, mas o risco político está nos itens. Fertilizantes, chips, IFAs, minerais críticos, energia e mobilidade reagem a relações bilaterais, preferências comerciais e choques internacionais.</p></div></section><section className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-card/60 p-4"><div className="ui-kicker">Oportunidades abertas</div><div className="mt-3 space-y-2">{oportunidades.map(o=>{const p=paises.find(x=>x.id===o.paisId);const item=o.produtoId?comercioExterior.itensEstrategicos?.[o.produtoId]:null;return <div key={o.id} className="rounded-2xl border border-border bg-panel/40 p-4"><div className="flex items-start gap-3">{item&&<IllustratedAsset src={item.imagem} label={item.nome} emoji={item.emoji} className="h-16 w-16 shrink-0"/>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black">{o.titulo}</div><div className="mt-1 text-[10px] text-info">{p?.nome||o.paisId} · {o.tipo.replaceAll('_',' ')}</div></div><span className="ui-chip">{fmt(o.valor)}</span></div><p className="mt-2 text-xs leading-relaxed text-muted">{o.texto}</p>{Object.keys(o.rivalidades||{}).length>0&&<div className="mt-2 text-[9px] font-black uppercase text-warning">Pode irritar: {Object.entries(o.rivalidades).filter(([,v])=>v<0).map(([id])=>partnerName(id)).join(' · ')}</div>}<button onClick={()=>accept(o.id)} className="ui-btn-secondary mt-3 text-[10px]"><Handshake size={13}/> Negociar acordo</button></div></div></div>})}{!oportunidades.length&&<div className="grid min-h-[240px] place-items-center text-center text-sm text-muted">Nenhuma oportunidade aberta. Visitas de Estado e pressões diplomáticas podem criar novas.</div>}</div></section></div>}
    {view==='exportacoes'&&<div className="grid min-h-0 flex-1 content-start gap-2 overflow-y-auto md:grid-cols-2 xl:grid-cols-3">{exp.map(([id,s])=><div key={id} className="rounded-2xl border border-border bg-card/60 p-4"><div className="flex items-center justify-between"><GameIcon icon={Ship} tone="success" size="sm"/><span className="text-lg font-black text-success">{fmt(s.valor)}</span></div><div className="mt-3 font-black">{s.nome}</div><div className="mt-1 text-[10px] text-muted">Potencial exportador {s.potencial}/100</div><div className="mt-3 h-1.5 rounded-full bg-bg"><div className="h-full rounded-full bg-success" style={{width:`${s.potencial}%`}}/></div><button onClick={()=>doExport(id)} className="ui-btn-secondary mt-4 w-full justify-center text-[10px]">Crédito à exportação</button></div>)}</div>}
    {view==='importacoes'&&<div className="grid min-h-0 flex-1 content-start gap-2 overflow-y-auto md:grid-cols-2 xl:grid-cols-3">{imp.map(([id,s])=><div key={id} className="rounded-2xl border border-border bg-card/60 p-4"><div className="flex items-center justify-between"><GameIcon icon={ArrowDownToLine} tone={s.dependencia>70?'danger':'warning'} size="sm"/><span className="text-lg font-black">{fmt(s.valor)}</span></div><div className="mt-3 font-black">{s.nome}</div><div className="mt-1 text-[10px] text-muted">Dependência externa {s.dependencia}/100</div><div className="mt-4 flex items-center justify-between rounded-xl border border-border bg-panel/40 p-3"><div><div className="ui-data-label">Tarifa setorial</div><div className="text-xl font-black">{s.tarifa}%</div></div><div className="flex gap-1"><button onClick={()=>doTariff(id,-2)} className="ui-btn-secondary px-3">−</button><button onClick={()=>doTariff(id,2)} className="ui-btn-secondary px-3">+</button></div></div></div>)}</div>}
    {view==='estrategicos'&&strategic&&<div className="grid min-h-0 flex-1 gap-3 xl:grid-cols-[1.05fr_.95fr]"><section className="grid min-h-0 content-start gap-2 overflow-y-auto pr-1 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><button key={item.id} onClick={()=>setItemId(item.id)} className={`rounded-2xl border p-3 text-left ${strategic.id===item.id?'border-info/45 bg-info/5':'border-border bg-card/55 hover:border-muted/60'}`}><div className="flex gap-3"><IllustratedAsset src={item.imagem} label={item.nome} emoji={item.emoji} className="h-16 w-16 shrink-0"/><div className="min-w-0"><div className="text-xs font-black">{item.nome}</div><div className="mt-1 text-[9px] uppercase text-muted">{item.categoria}</div><div className="mt-2 text-sm font-black">{fmt(item.valor)}</div></div></div><div className="mt-3 flex items-center justify-between text-[9px]"><span className="ui-chip">{flowLabel[item.tipo]||item.tipo}</span><span className={(item.sensibilidade||0)>=90?'text-danger':'text-warning'}>sensib. {item.sensibilidade}</span></div></button>)}</section><aside className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-card/65 p-5"><div className="flex gap-4"><IllustratedAsset src={strategic.imagem} label={strategic.nome} emoji={strategic.emoji} className="h-28 w-28 shrink-0"/><div><div className="ui-kicker">Ativo estratégico</div><h3 className="mt-1 text-2xl font-black">{strategic.nome}</h3><div className="mt-2 flex flex-wrap gap-1"><span className="ui-chip">{strategic.categoria}</span><span className="ui-chip text-info">{flowLabel[strategic.tipo]}</span></div></div></div><p className="mt-4 text-xs leading-relaxed text-muted">{strategic.descricao}</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Fluxo mensal" value={fmt(strategic.valor)}/><Mini label="Potencial" value={`${strategic.potencial}/100`}/><Mini label="Dependência externa" value={`${strategic.dependencia}/100`} danger={(strategic.dependencia||0)>=80}/><Mini label="Capacidade doméstica" value={`${strategic.capacidadeDomestica}/100`}/></div><div className="mt-5"><div className="ui-data-label">Parceiros críticos</div><div className="mt-2 flex flex-wrap gap-2">{(strategic.parceiros||[]).map(id=><span key={id} className="ui-chip">{partnerName(id)} · pref. {Number(preferences[id]||0)>0?'+':''}{Number(preferences[id]||0)}</span>)}</div></div><div className="mt-4 rounded-xl border border-warning/20 bg-warning/5 p-3"><ShieldAlert size={15} className="text-warning"/><div className="mt-2 text-xs font-black">Sensibilidade geopolítica {strategic.sensibilidade}/100</div><p className="mt-1 text-[10px] leading-relaxed text-muted">Acordos exclusivos, sanções, tarifas ou deterioração diplomática podem alterar este item mesmo quando o setor agregado continua saudável.</p></div></aside></div>}
    {view==='mercados'&&<div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[1fr_.8fr]"><section className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-card/60 p-4"><div className="ui-kicker">Principais parceiros</div><div className="mt-3 space-y-2">{parceiros.map(([id,p])=><div key={id} className="grid grid-cols-[1fr_auto_auto_auto] items-center gap-4 rounded-xl border border-border bg-panel/35 p-3"><div><div className="text-xs font-black">{p.nome}</div><div className="text-[9px] text-muted">Acesso {p.acesso}/100 · preferência {Number(preferences[id]||0)>0?'+':''}{Number(preferences[id]||0)}</div></div><div className="text-right"><div className="text-[9px] text-muted">EXP</div><b className="text-success">{fmt(p.exportacoes)}</b></div><div className="text-right"><div className="text-[9px] text-muted">IMP</div><b className="text-warning">{fmt(p.importacoes)}</b></div><Gauge size={15} className={Number(preferences[id]||0)<-3?'text-danger':Number(preferences[id]||0)>3?'text-success':'text-muted'}/></div>)}</div></section><aside className="min-h-0 overflow-y-auto rounded-2xl border border-border bg-panel/40 p-4"><Network size={18} className="text-warning"/><div className="mt-3 text-lg font-black">Concorrência geopolítica</div><p className="mt-2 text-xs leading-relaxed text-muted">Preferência comercial não é neutra. Acordos tecnológicos, minerais, automotivos e de infraestrutura alteram a percepção dos concorrentes.</p><div className="mt-4 space-y-2">{tensions.map(t=><div key={t.id} className="rounded-xl border border-warning/20 bg-warning/5 p-3"><div className="text-xs font-black">{partnerName(t.paisId)}</div><div className="mt-1 text-[10px] text-muted">{t.titulo}</div><div className="mt-2 text-[9px] font-black uppercase text-warning">tensão {Math.round(t.intensidade||0)}/100</div></div>)}{!tensions.length&&<div className="rounded-xl border border-dashed border-border p-4 text-xs text-muted">Nenhuma rivalidade comercial aguda no momento.</div>}</div></aside></div>}
  </div>;
}
function Card({icon:Icon,label,value,tone='info'}){return <div className="rounded-2xl border border-border bg-card/65 p-4"><GameIcon icon={Icon} tone={tone} size="sm"/><div className="mt-3 ui-data-label">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>}
function Mini({label,value,danger=false}){return <div className="rounded-xl border border-border bg-panel/35 p-3"><div className="ui-data-label">{label}</div><div className={`mt-1 text-lg font-black ${danger?'text-danger':''}`}>{value}</div></div>}
